// Seed proposal — non-food: Drogerie, Domácnost, Děti and Ostatní.
import { existingType as ex, newType as nw, type SeedType } from './types'

const D = 'Drogerie' as const
const H = 'Domácnost' as const
const K = 'Děti' as const
const O = 'Ostatní' as const

export const NEPOTRAVINOVE: SeedType[] = [
  // --- Drogerie: praní -----------------------------------------------------------------------------------------------
  ex('praci-prasek', 'Prací prášek', D, 'Praní', 'kg', 'určení prášku', [
    ['Prací prášek na bílé', 'univerzální a bílé prádlo'],
    ['Prací prášek na barevné', 'prášek pro barevné prádlo'],
    ['Prací prášek na černé', 'prášek na tmavé a černé prádlo'],
    ['Prací prášek na jemné prádlo', 'jemné prádlo, vlna, hedvábí'],
    ['Prací prášek hypoalergenní', 'prášek pro citlivou pokožku, dětské prádlo'],
  ]),
  ex('praci-gel', 'Prací gel', D, 'Praní', 'l', 'určení gelu', [
    ['Prací gel univerzální', 'gel na bílé i barevné prádlo'],
    ['Prací gel na barevné', 'gel na barevné prádlo'],
    ['Prací gel na černé a tmavé', 'gel na tmavé a černé prádlo'],
    ['Prací gel na jemné prádlo', 'gel na jemné prádlo, vlna a hedvábí'],
    ['Prací gel hypoalergenní', 'gel pro citlivou pokožku'],
    ['Prací gel sportovní', 'gel na funkční prádlo'],
  ]),
  nw('praci-kapsle', 'Prací kapsle', D, 'Praní', 'ks', 'určení kapslí', [
    ['Prací kapsle univerzální', 'kapsle na bílé i barevné prádlo'],
    ['Prací kapsle na barevné', 'kapsle na barevné prádlo'],
    ['Prací kapsle na černé', 'kapsle na tmavé prádlo'],
    ['Prací kapsle hypoalergenní', 'kapsle pro citlivou pokožku'],
  ]),
  ex('avivaz', 'Aviváž', D, 'Praní', 'l', 'forma aviváže', [
    ['Aviváž tekutá', 'tekutá aviváž běžná'],
    ['Aviváž koncentrovaná', 'koncentrovaná aviváž'],
    ['Parfém do prádla', 'vonné perly, vonné kuličky do pračky'],
    ['Aviváž hypoalergenní', 'aviváž pro citlivou pokožku'],
  ]),
  nw('praci-prisady', 'Přísady do praní', D, 'Praní', 'kg', 'funkce přísady', [
    ['Odvápňovač a změkčovač', 'změkčovač vody, odvápňovač pračky'],
    ['Bělidlo', 'bělidlo na prádlo'],
    ['Odstraňovač skvrn', 'odstraňovač skvrn, žlučové mýdlo'],
    ['Čistič pračky', 'čistič pračky, tablety'],
    ['Zachytávač barev', 'ubrousky proti zabarvení prádla'],
    ['Škrob a apretura', 'škrob na prádlo, apretura'],
  ]),

  // --- Drogerie: mytí nádobí --------------------------------------------------------------------------------------------
  ex('tablety-do-mycky', 'Tablety do myčky', D, 'Mytí nádobí', 'ks', 'forma myčkového přípravku', [
    ['Tablety do myčky all in one', 'víceúčelové tablety'],
    ['Tablety do myčky základní', 'tablety bez přísad'],
    ['Kapsle do myčky', 'gelové kapsle do myčky'],
    ['Prášek do myčky', 'práškový mycí přípravek'],
    ['Gel do myčky', 'mycí gel do myčky'],
  ]),
  nw('myci-prisady-mycka', 'Doplňky do myčky', D, 'Mytí nádobí', 'kg', 'funkce přípravku', [
    ['Leštidlo do myčky', 'leštidlo, oplachovač'],
    ['Sůl do myčky', 'regenerační sůl'],
    ['Čistič myčky', 'čistič myčky, osvěžovač myčky'],
    ['Osvěžovač myčky', 'vůně do myčky'],
  ]),
  ex('jar', 'Prostředek na nádobí', D, 'Mytí nádobí', 'l', 'typ prostředku', [
    ['Prostředek na ruční mytí nádobí', 'tekutý prostředek na mytí nádobí'],
    ['Prostředek na nádobí koncentrát', 'koncentrát na mytí nádobí'],
    ['Prostředek na nádobí hypoalergenní', 'pro citlivou pokožku'],
    ['Prostředek na nádobí antibakteriální', 'antibakteriální'],
  ]),

  // --- Drogerie: čištění domácnosti -------------------------------------------------------------------------------------
  ex('univerzalni-cistic', 'Univerzální čistič', D, 'Čištění domácnosti', 'l', 'povrch nebo účel', [
    ['Čistič na podlahy', 'podlahový čistič, mop'],
    ['Čistič na nábytek', 'leštěnka na nábytek'],
    ['Čistič na sporák a troubu', 'odmašťovač, čistič na trouby'],
    ['Čistič koberců a čalounění', 'čistič koberců, čištění čalounění'],
    ['Univerzální čistič spray', 'čistič ve spreji pro více povrchů'],
  ]),
  ex('cistic-koupelny', 'Čistič koupelny', D, 'Čištění domácnosti', 'l', 'oblast koupelny', [
    ['Čistič na vodní kámen', 'odvápňovač, čistič vodního kamene'],
    ['Čistič sprchových koutů', 'čistič skla ve sprše'],
    ['Čistič odpadů', 'čistič odpadu, tekutý, granulát'],
    ['Čistič vany a umyvadla', 'čistič vany a keramiky'],
  ]),
  ex('cistic-wc', 'Čistič WC', D, 'Čištění domácnosti', 'l', 'forma čističe', [
    ['WC gel', 'WC gel s tryskou'],
    ['WC tablety a závěsy', 'tablety do nádržky, závěsy'],
    ['WC pěna a spray', 'pěna na WC'],
    ['WC čistič na vodní kámen', 'odvápňovač WC'],
  ]),
  nw('osvezovace-vzduchu', 'Osvěžovače vzduchu', D, 'Čištění domácnosti', 'ks', 'forma osvěžovače', [
    ['Osvěžovač ve spreji', 'sprej na vzduch'],
    ['Elektrický osvěžovač', 'elektrický difuzér, náplň'],
    ['Gelový osvěžovač', 'gelové osvěžovače, závěsné'],
    ['Auto osvěžovač', 'osvěžovač do auta'],
    ['Vonná svíčka a vonný difuzér', 'aroma svíčky, tyčinky'],
  ]),
  nw('desinfekce-hygiena', 'Dezinfekce', D, 'Čištění domácnosti', 'l', 'určení dezinfekce', [
    ['Dezinfekce na ruce', 'gel na ruce, sprej'],
    ['Dezinfekce na povrchy', 'sprej na povrchy, ubrousky'],
    ['Dezinfekce na prádlo', 'prostředek pro dezinfekci prádla'],
    ['Dezinfekční ubrousky', 'vlhčené dezinfekční ubrousky'],
  ]),
  nw('ochrana-proti-skudcum', 'Ochrana proti škůdcům', D, 'Čištění domácnosti', 'ks', 'cílový škůdce', [
    ['Repelent proti komárům', 'repelent na kůži, spirály'],
    ['Přípravek proti molům', 'moly, šatní'],
    ['Přípravek proti mravencům a šváby', 'nástrahy, návnady'],
    ['Past na myši', 'pasti na hlodavce'],
    ['Odpuzovač hmyzu', 'ultrazvukové, přírodní odpuzovače'],
  ]),

  // --- Drogerie: kosmetika a hygiena --------------------------------------------------------------------------------------
  ex('sampon', 'Šampon', D, 'Kosmetika', 'l', 'typ vlasů nebo účel šamponu', [
    ['Šampon na mastné vlasy', 'šampon pro mastné vlasy'],
    ['Šampon na suché vlasy', 'šampon pro suché a poškozené vlasy'],
    ['Šampon proti lupům', 'šampon proti lupům'],
    ['Šampon pro objem', 'šampon pro jemné vlasy a objem'],
    ['Šampon na barvené vlasy', 'ochrana barvy'],
    ['Šampon 2v1', 'šampon s kondicionérem'],
    ['Pánský šampon', 'pánský šampon, sprchový gel 2v1'],
  ]),
  nw('kondicioner-vlasy', 'Kondicionéry a vlasová péče', D, 'Kosmetika', 'l', 'druh vlasové péče', [
    ['Kondicionér', 'kondicionér po mytí vlasů'],
    ['Maska na vlasy', 'maska, intenzivní péče'],
    ['Olej a sérum na vlasy', 'olej, sérum, kapky'],
    ['Stylingový přípravek', 'lak, gel, pěnové tužidlo, vosk'],
    ['Barva na vlasy', 'barvy na vlasy'],
    ['Suchý šampon', 'suchý šampon ve spreji'],
  ]),
  ex('sprchovy-gel', 'Sprchový gel', D, 'Kosmetika', 'l', 'určení sprchového gelu', [
    ['Sprchový gel dámský', 'dámský sprchový gel'],
    ['Sprchový gel pánský', 'pánský sprchový gel'],
    ['Sprchový gel pro citlivou nebo suchou pokožku', 'hypoalergenní a hydratační sprchový gel'],
    ['Sprchový olej a pěna', 'sprchový olej, sprchová pěna'],
  ]),
  ex('mydlo', 'Mýdlo', D, 'Hygiena', 'ks', 'forma mýdla', [
    ['Tuhé mýdlo', 'tuhé mýdlo, kostka'],
    ['Tekuté mýdlo', 'tekuté mýdlo s dávkovačem, náplň'],
    ['Pěnové mýdlo', 'pěnové mýdlo, náplň do pěnového dávkovače'],
  ]),
  ex('zubni-pasta', 'Zubní pasta', D, 'Hygiena', 'kg', 'hlavní účel zubní pasty', [
    ['Zubní pasta běžná', 'zubní pasta s fluoridem pro každodenní použití bez specifického účelu'],
    ['Zubní pasta bělicí', 'bělicí pasta'],
    ['Zubní pasta pro citlivé zuby', 'pasta pro citlivé zuby'],
    ['Zubní pasta na dásně', 'ochrana dásní, parodontóza'],
  ]),
  ex('ustni-hygiena', 'Ústní hygiena', D, 'Hygiena', 'ks', 'druh pomůcky', [
    ['Zubní kartáček manuální', 'manuální zubní kartáček'],
    ['Elektrický zubní kartáček a hlavice', 'elektrický kartáček, náhradní hlavice'],
    ['Ústní voda', 'ústní voda, ústní sprej'],
    ['Zubní nit a mezizubní kartáček', 'zubní nit, mezizubní kartáčky, párátka'],
    ['Zubní pásky a ošetření', 'bělicí pásky, fixace, pasta na zubní protézu'],
  ]),
  ex('deodoranty', 'Deodorant', D, 'Hygiena', 'ks', 'forma deodorantu', [
    ['Deodorant sprej', 'sprej'],
    ['Deodorant roll-on', 'roll-on'],
    ['Deodorant tuhý', 'tuhá tyčinka, stick'],
    ['Deodorant krémový', 'krémový deodorant v tubě nebo kelímku'],
  ]),
  ex('holeni', 'Holení', D, 'Hygiena', 'ks', 'druh pomůcky nebo přípravku', [
    ['Holicí strojek a břity', 'holicí strojek, náhradní hlavice'],
    ['Jednorázový holicí strojek', 'jednorázové'],
    ['Pěna a gel na holení', 'pěna na holení, gel, krém'],
    ['Voda po holení', 'voda po holení, balzám'],
    ['Depilace', 'depilační pásky, krém, vosk'],
  ]),
  ex('damska-hygiena', 'Dámská hygiena', D, 'Hygiena', 'ks', 'druh hygienické pomůcky', [
    ['Menstruační vložky', 'vložky, noční i denní'],
    ['Tampony', 'tampony'],
    ['Slipové vložky', 'slipové, intimní vložky'],
    ['Menstruační kalíšek a kalhotky', 'kalíšky, savé kalhotky'],
    ['Intimní hygiena', 'intimní gel, ubrousky, mýdlo'],
  ]),
  ex('vlhcene-ubrousky', 'Vlhčené ubrousky', D, 'Hygiena', 'ks', 'určení ubrousků', [
    ['Vlhčené ubrousky univerzální', 'všestranné ubrousky'],
    ['Vlhčené ubrousky na obličej', 'odličovací a čisticí'],
    ['Vlhčené ubrousky toaletní', 'vlhčený toaletní papír'],
    ['Vlhčené ubrousky na ruce', 'osvěžující na ruce'],
    ['Vlhčené ubrousky intimní', 'intimní ubrousky'],
  ]),
  nw('pece-o-telo', 'Péče o tělo', D, 'Kosmetika', 'ks', 'druh tělové péče', [
    ['Tělové mléko a krém', 'tělové mléko, tělové máslo'],
    ['Krém na ruce', 'krém na ruce, nehty'],
    ['Opalovací krém', 'opalovací krém, mléko po opalování'],
    ['Olej na tělo', 'tělový olej, masážní olej'],
    ['Peeling', 'tělový peeling, scrub'],
    ['Sprej proti slunci', 'ochrana před sluncem ve spreji'],
  ]),
  ex('pece-o-plet', 'Péče o pleť', D, 'Kosmetika', 'ks', 'druh pleťové péče', [
    ['Pleťový krém', 'denní a noční krém'],
    ['Pleťová maska', 'pleťová maska, textilní maska'],
    ['Odličovací přípravek', 'micelární voda, odličovací mléko'],
    ['Čisticí gel na obličej', 'čisticí gel, pěna'],
    ['Oční krém a sérum', 'oční krém, sérum'],
    ['Krém s UV filtrem', 'pleťový krém s SPF'],
  ]),
  ex('dekorativni-kosmetika', 'Dekorativní kosmetika', D, 'Kosmetika', 'ks', 'část obličeje', [
    ['Řasenka a oční linky', 'řasenka, oční tužka'],
    ['Rtěnka a lesk', 'rtěnka, lesk na rty, balzám'],
    ['Make-up a pudr', 'make-up, pudr, korektor'],
    ['Tvářenka a bronzer', 'tvářenka, bronzer, rozjasňovač'],
    ['Lak na nehty', 'lak, odlakovač'],
    ['Stíny a paletky', 'oční stíny, paletky'],
  ]),
  nw('parfemy', 'Parfémy a vůně', D, 'Kosmetika', 'ks', 'forma vůně', [
    ['Parfémová voda', 'parfémová voda dámská, pánská'],
    ['Toaletní voda', 'toaletní voda'],
    ['Tělový sprej', 'tělová mlha, deosprej'],
  ]),

  // --- Drogerie: zdraví a doplňky ---------------------------------------------------------------------------------------
  nw('vitaminy-doplnky', 'Vitamíny a doplňky stravy', D, 'Zdraví a doplňky stravy', 'ks', 'účel doplňku', [
    ['Multivitamín', 'multivitamíny pro dospělé a děti'],
    ['Vitamín C', 'vitamín C, šípky'],
    ['Vitamín D', 'vitamín D, kapky, tobolky'],
    ['Hořčík a minerály', 'hořčík, zinek, železo'],
    ['Probiotika', 'probiotika, trávení'],
    ['Omega-3', 'rybí olej, omega 3'],
    ['Kloubní výživa', 'kolagen, glukosamin'],
    ['Proteiny a sportovní výživa', 'proteinový prášek, BCAA, kreatin'],
    ['Bylinné doplňky', 'bylinné kapsle, čaje na zdraví'],
  ]),
  nw('lekarnicka-volne-prodejne', 'Volně prodejné léky a lékárnička', D, 'Zdraví a doplňky stravy', 'ks', 'účel přípravku', [
    ['Léky proti bolesti', 'ibuprofen, paracetamol, aspirin'],
    ['Léky na nachlazení', 'kapky do nosu, sirupy, pastilky na kašel'],
    ['Léky na trávení', 'živočišné uhlí, probiotika při průjmu'],
    ['Náplasti a obvazy', 'náplasti, obvazy, gáza'],
    ['Teploměr a zdravotnické pomůcky', 'teploměry, tlakoměry, rouška'],
    ['Alergie a repelent', 'antihistaminika, repelenty na klíšťata'],
    ['Pomůcky na rány', 'dezinfekce ran, mast, gel'],
  ]),
  nw('brejle-doplnky', 'Doplňky a oblečení z drogerie', D, 'Doplňky a oblečení', 'ks', 'druh doplňku', [
    ['Ponožky a punčochy', 'ponožky, punčochové kalhoty'],
    ['Brýle', 'dioptrické brýle, brýle na čtení, sluneční'],
    ['Gumičky a sponky do vlasů', 'vlasové doplňky, sponky, gumičky'],
    ['Peněženky a tašky', 'drobné příslušenství'],
  ]),

  // --- Domácnost -------------------------------------------------------------------------------------------------------
  ex('toaletni-papir', 'Toaletní papír', H, 'Papír', 'ks', 'vrstvy a materiál', [
    ['Toaletní papír 2vrstvý', 'dvouvrstvý toaletní papír'],
    ['Toaletní papír 3vrstvý', 'třívrstvý toaletní papír'],
    ['Toaletní papír 4vrstvý', 'čtyřvrstvý toaletní papír'],
    ['Toaletní papír z recyklovaného papíru', 'recyklovaný, ekologický'],
    ['Toaletní papír vlhčený', 'vlhčený toaletní papír'],
    ['Toaletní papír jumbo', 'velké role pro komerční užití'],
  ]),
  ex('kuchynske-uterky', 'Kuchyňské utěrky', H, 'Papír', 'ks', 'role nebo balení utěrek', [
    ['Papírové utěrky na roli', 'kuchyňské papírové utěrky v roli'],
    ['Papírové ubrousky', 'papírové ubrousky, ubrousky na stůl'],
    ['Papírové kapesníky', 'kapesníky v krabičce, balíček'],
    ['Papírové talíře a kelímky', 'jednorázové nádobí'],
  ]),
  nw('uterky-hadry', 'Hadry, utěrky a houbičky', H, 'Kuchyň', 'ks', 'materiál a použití', [
    ['Mikrovláknová utěrka', 'mikrovlákno, hadřík'],
    ['Houbička na nádobí', 'houbičky na mytí nádobí'],
    ['Drátěnka', 'drátěnka, dračí kůže'],
    ['Utěrka na nádobí', 'utěrka textilní, kuchyňská'],
    ['Hadr na podlahu', 'hadr na podlahu, mop'],
    ['Kartáč a kartáčky', 'kartáče na nádobí, kartáčky na toaletu'],
    ['Rukavice na úklid', 'gumové, latexové rukavice'],
  ]),
  nw('kuchynske-potreby', 'Kuchyňské potřeby', H, 'Kuchyň', 'ks', 'druh potřeby', [
    ['Hrnce a pánve', 'hrnec, pánev, pekáč'],
    ['Kuchyňské nože', 'nůž, nože, brousek'],
    ['Příbory a nádobí', 'příbor, talíře, hrnky'],
    ['Pečicí formy', 'formy na pečení, plechy'],
    ['Dózy a skladování', 'potravinové dózy, boxy, lahve'],
    ['Kuchyňské pomůcky', 'struhadlo, škrabka, ošatka, naběračka'],
    ['Termosky a láhve', 'termosky, termohrnky, láhve'],
  ]),
  ex('alobal', 'Alobal', H, 'Kuchyň', 'ks', 'druh fólie', [
    ['Alobal', 'hliníková fólie na pečení'],
    ['Potravinářská fólie', 'stretch fólie, potravinová fólie'],
    ['Pečicí papír', 'pečicí papír, papír na pečení'],
    ['Sáčky na potraviny', 'sáčky na zamrazení, mikrotenové'],
    ['Zásobníky na potraviny', 'svačinové krabičky, vakuové sáčky'],
  ]),
  ex('pytle-na-odpadky', 'Pytle na odpadky', H, 'Úklid', 'ks', 'objem pytlů', [
    ['Pytle na odpadky malé', 'do 35 l'],
    ['Pytle na odpadky střední', 'do 60 l'],
    ['Pytle na odpadky velké', 'nad 60 l'],
    ['Pytle na bioodpad', 'kompostovatelné pytle'],
    ['Sáčky na psí exkrementy', 'sáčky na výkaly'],
  ]),
  nw('uklid-pomucky', 'Úklidové pomůcky', H, 'Úklid', 'ks', 'druh pomůcky', [
    ['Mop a kbelík', 'mop, kbelík, ždímací'],
    ['Smeták a lopatka', 'smetáky, lopatky, zametací set'],
    ['Prachovka', 'prachovka, stěrka na prach'],
    ['Stěrka na okna', 'stěrky, teleskopické tyče'],
    ['Vysavače a sáčky', 'vysavače, sáčky, filtry'],
  ]),
  nw('svetlo-baterie', 'Světlo a baterie', H, 'Ostatní', 'ks', 'druh zboží', [
    ['Žárovky', 'žárovka LED, halogen'],
    ['Baterie jednorázové', 'AA, AAA, tužkové'],
    ['Baterie nabíjecí', 'akumulátory, nabíječka'],
    ['Svíčky', 'svíčky, čajové, adventní'],
    ['Zapalovače a sirky', 'zapalovače, sirky, podpalovače'],
    ['Svítilny a čelovky', 'ruční a čelová svítilna'],
    ['Prodlužovací kabely', 'prodlužovačky, rozdvojky'],
  ]),
  nw('zahrada-rostliny', 'Zahrada — rostliny a substráty', H, 'Zahrada', 'ks', 'druh zahradního zboží', [
    ['Hnojiva', 'hnojivo, kompostér, vermikompost'],
    ['Substráty a zemina', 'zahradnický substrát, kůra, rašelina'],
    ['Osivo a cibuloviny', 'semena, osiva, cibulky'],
    ['Květináče a truhlíky', 'květináče, truhlíky, podmisky'],
    ['Zahradní nářadí', 'rýč, hrábě, nůžky, rukavice'],
    ['Rostliny v květináči', 'pokojové rostliny, řezané květiny'],
    ['Ochranné prostředky rostlin', 'přípravky proti škůdcům na zahradě'],
  ]),
  nw('domaci-textil', 'Domácí textil', H, 'Ostatní', 'ks', 'druh textilu', [
    ['Ložní prádlo', 'povlečení, prostěradla'],
    ['Ručníky a osušky', 'ručníky, osušky'],
    ['Utěrky a zástěry', 'zástěra, chňapky'],
    ['Přikrývky a polštáře', 'deky, polštáře, peřiny'],
    ['Záclony a závěsy', 'záclony, závěsy, rolety'],
  ]),
  nw('domaci-mazlicci', 'Krmivo a potřeby pro domácí mazlíčky', O, 'Ostatní zboží', 'kg', 'druh zvířete a typ zboží', [
    ['Krmivo pro psy suché', 'granule pro psy'],
    ['Krmivo pro psy mokré', 'konzervy, kapsičky pro psy'],
    ['Krmivo pro kočky suché', 'granule pro kočky'],
    ['Krmivo pro kočky mokré', 'konzervy, kapsičky pro kočky'],
    ['Pamlsky pro psy', 'pamlsky, kosti, žvýkací'],
    ['Pamlsky pro kočky', 'pamlsky pro kočky'],
    ['Stelivo pro kočky', 'kočkolit, stelivo'],
    ['Krmivo pro hlodavce a ptáky', 'krmivo pro králíky, morčata, ptáky'],
    ['Krmivo pro ryby', 'krmivo pro akvarijní ryby'],
    ['Pomůcky pro mazlíčky', 'hračky, obojky, misky, pelíšky'],
  ]),

  // --- Děti ------------------------------------------------------------------------------------------------------------
  ex('pleny', 'Pleny', K, 'Pleny', 'ks', 'velikost nebo typ plenek', [
    ['Pleny novorozenecké', 'velikost 1, newborn'],
    ['Pleny pro malé děti', 'velikost 2–4'],
    ['Pleny pro větší děti', 'velikost 5–6'],
    ['Plenkové kalhotky', 'pull-up kalhotky, pants'],
    ['Plavky a noční plenky', 'plavací pleny, noční kalhotky'],
    ['Látkové pleny', 'látkové pleny, vložky'],
  ]),
  nw('detska-vyziva-mleko', 'Kojenecká výživa', K, 'Kojenecké mléko', 'kg', 'věk dítěte', [
    ['Počáteční mléko', 'mléko od narození, stage 1'],
    ['Pokračovací mléko', 'od 6. měsíce, stage 2'],
    ['Batolecí mléko', 'od 12. měsíce, stage 3'],
    ['Speciální kojenecké mléko', 'anti-reflux, hypoalergenní, bez laktózy'],
    ['Mléko pro děti předškolního věku', 'růstové mléko'],
  ]),
  nw('detske-prikrmy-druhy', 'Příkrmy', K, 'Příkrmy', 'kg', 'forma příkrmu', [
    ['Zeleninový příkrm', 'zeleninové pyré'],
    ['Ovocný příkrm', 'ovocné pyré, kapsička'],
    ['Masový příkrm', 'maso se zeleninou, příkrm s masem'],
    ['Příkrm s obilovinou', 'ovocný s cereáliemi, kaše'],
    ['Mléčný příkrm', 'příkrm s jogurtem, tvarohový'],
    ['Večerní příkrm', 'večerní kaše, sladký příkrm'],
  ]),
  nw('detske-kase', 'Dětské kaše a cereálie', K, 'Kaše a cereálie', 'kg', 'typ kaše', [
    ['Mléčná kaše', 'instantní kaše s mlékem'],
    ['Nemléčná kaše', 'kaše bez mléka, vodní'],
    ['Obilná kaše', 'ovesná, rýžová, kukuřičná, špaldová kaše'],
    ['Ovocná kaše', 'kaše s ovocem'],
    ['Dětské cereálie', 'cereálie pro děti, müsli pro děti'],
  ]),
  nw('detske-svacinky', 'Dětské svačinky', K, 'Dětské svačinky', 'ks', 'druh svačinky', [
    ['Dětský piškot a sušenka', 'rozpustné piškoty, sušenky pro děti'],
    ['Dětský křupek', 'křupky, pufované pro děti'],
    ['Ovocná tyčinka pro děti', 'ovocné tyčinky'],
    ['Dětský jogurt', 'jogurty pro děti, dezerty'],
    ['Dětský pudink a dezert', 'mléčné dezerty pro děti'],
  ]),
  ex('detske-napoje', 'Dětské nápoje', K, 'Dětské nápoje', 'l', 'druh nápoje', [
    ['Dětský čaj', 'bylinný čaj pro děti, instantní'],
    ['Dětská voda', 'voda pro kojence a děti'],
    ['Dětský džus', 'džus pro děti, ovocný nápoj'],
    ['Dětská šťáva', 'šťáva, kapsička'],
  ]),
  ex('detska-kosmetika', 'Dětská kosmetika', K, 'Dětská kosmetika', 'ks', 'druh dětské péče', [
    ['Dětský krém na zadeček', 'pasta na opruzeniny'],
    ['Dětský olej a mléko', 'tělový olej, mléko'],
    ['Dětský pudr', 'pudr, zásyp'],
    ['Dětský krém na obličej', 'krém, ochranný krém'],
    ['Dětské mycí gely', 'koupel, mycí gel na tělo a vlasy'],
    ['Dětské ubrousky', 'vlhčené ubrousky pro děti'],
  ]),
  nw('detske-potreby', 'Dětské potřeby', K, 'Dětské potřeby', 'ks', 'druh potřeby', [
    ['Dětské lahve a dudlíky', 'kojenecké lahve, dudlíky, savičky'],
    ['Kojicí pomůcky', 'prsní vložky, odsávačka'],
    ['Dětské příbory a nádobí', 'talířky, příbory, hrnky'],
    ['Dětské kočárky a autosedačky', 'kočárky, autosedačky'],
    ['Hygienické pomůcky pro děti', 'nočníky, redukce na WC, sterilizátory'],
  ]),
  nw('hracky', 'Hračky', K, 'Hračky', 'ks', 'druh hračky', [
    ['Stavebnice', 'lego, kostky, stavebnice'],
    ['Panenky a plyšové hračky', 'panenky, plyšáci'],
    ['Autíčka a modely', 'auta, vlaky, modely'],
    ['Společenské hry a puzzle', 'hry, puzzle, karty'],
    ['Výtvarné potřeby', 'pastelky, plastelína, barvy'],
    ['Venkovní hračky', 'kola, koloběžky, míče, písek'],
    ['Hračky pro nejmenší', 'chrastítka, hrací deky'],
    ['Školní potřeby', 'sešity, penály, aktovky'],
  ]),

  // --- Ostatní ---------------------------------------------------------------------------------------------------------
  nw('tabak-vyrobky', 'Tabák a související výrobky', O, 'Tabák a e-cigarety', 'ks', 'druh výrobku', [
    ['Cigarety', 'krabička cigaret'],
    ['Tabák na vlastní výrobu', 'dýmkový tabák, balíček tabáku'],
    ['Doutníky', 'doutníky, doutníčky'],
    ['Papírky a filtry', 'cigaretové papírky, filtry, dutinky'],
    ['E-cigarety a náplně', 'elektronické cigarety, liquidy, kapsle'],
    ['Nikotinové sáčky', 'nikotinové sáčky, žvýkačky'],
  ]),
  nw('elektronika-doplnky', 'Elektronika a příslušenství', O, 'Elektronika', 'ks', 'druh elektroniky', [
    ['Kabely a nabíječky', 'USB kabely, nabíječky, adaptéry'],
    ['Sluchátka a reproduktory', 'sluchátka, reproduktory'],
    ['Paměťové karty a USB flash', 'paměťové karty, flash disky'],
    ['Mobilní příslušenství', 'pouzdra, ochranné sklo, držáky'],
    ['Drobná elektronika', 'budík, kalkulačka, hodinky'],
  ]),
  nw('obleceni-obuv-zbozi', 'Oblečení a obuv', O, 'Oblečení a obuv', 'ks', 'druh oblečení', [
    ['Pánské oblečení', 'tričko, košile, kalhoty'],
    ['Dámské oblečení', 'dámské tričko, šaty, legíny'],
    ['Dětské oblečení', 'dětské oblečení'],
    ['Obuv', 'boty, pantofle, žabky'],
    ['Spodní prádlo', 'spodní prádlo, ponožky'],
    ['Sportovní oblečení', 'sportovní'],
  ]),
  nw('auto-doplnky', 'Auto — doplňky a chemie', O, 'Ostatní zboží', 'ks', 'druh zboží', [
    ['Autokosmetika', 'autošampon, vosk, čističe'],
    ['Motorové oleje a kapaliny', 'olej, chladicí kapalina, ostřikovač'],
    ['Stěrače a žárovky', 'stěrače, žárovky do auta'],
    ['Autodoplňky', 'držáky, koberečky, osvěžovače'],
  ]),
  nw('sezonni-zbozi', 'Sezónní zboží', O, 'Ostatní zboží', 'ks', 'druh sezóny', [
    ['Vánoční dekorace', 'vánoční ozdoby, stromečky, řetězy'],
    ['Velikonoční dekorace', 'velikonoční dekorace, kraslice'],
    ['Zimní doplňky', 'rukavice, čepice, šály'],
    ['Letní doplňky', 'plavky, slunečníky, opalovací doplňky'],
    ['Dárkové zboží', 'dárkové tašky, balicí papír'],
    ['Kancelářské potřeby', 'tužky, sešity, lepicí pásky'],
  ]),
]
