// Seed proposal — Potraviny, fresh goods: dairy, eggs, bakery, meat, fish, fruit and vegetables.
import { existingType as ex, newType as nw, type SeedType } from './types'

const P = 'Potraviny' as const

export const POTRAVINY_CERSTVE: SeedType[] = [
  // --- Mléčné výrobky -----------------------------------------------------------------------------
  ex('maslo', 'Máslo', P, 'Mléčné výrobky', 'kg', 'způsob zpracování a úprava másla', [
    ['Čerstvé máslo', 'máslo z pasterované smetany, kostka nebo kelímek'],
    ['Přepuštěné máslo', 'přepuštěné máslo, ghí, máslo bez vody a bílkovin'],
    ['Pomazánkové máslo', 'máslo upravené na mazání, např. s přídavkem rostlinného oleje', 'tvrdé kostkové máslo'],
    ['Ochucené máslo', 'máslo s bylinkami, česnekem nebo solí s příchutí', 'čisté máslo bez příměsí'],
  ]),
  ex('jogurt-bily', 'Bílý jogurt', P, 'Mléčné výrobky', 'kg', 'typ bílého jogurtu', [
    ['Bílý jogurt natur', 'přírodní jogurt bez příchuti a bez přidaného ovoce'],
    ['Řecký jogurt', 'jogurt řeckého typu, hustý, scezený'],
    ['Smetanový jogurt', 'bílý jogurt s vyšším podílem tuku, smetanový typ'],
    ['Bílý jogurt bez laktózy', 'bílý jogurt s deklarovaným obsahem laktózy pod limitem'],
    ['Probiotický bílý jogurt', 'bílý jogurt s deklarovanou probiotickou kulturou', 'ochucené jogurty'],
  ]),
  nw('jogurt-ochuceny', 'Ochucený jogurt', P, 'Mléčné výrobky', 'kg', 'druh příchuti nebo příměsi', [
    ['Ovocný jogurt', 'jogurt s ovocnou složkou nebo příchutí ovoce'],
    ['Jogurt s kousky ovoce', 'jogurt s viditelnými kousky ovoce'],
    ['Jogurt s čokoládou nebo karamelem', 'sladké příchutě čokoláda, karamel, vanilka, oříšek'],
    ['Jogurt s cereáliemi', 'jogurt s oddělenou nebo smíchanou cereální složkou'],
    ['Dvoukomorový jogurt', 'jogurt s oddělenou přísadou v druhé komoře kelímku', 'jogurt s ovocem zamíchaným dovnitř'],
  ]),
  nw('jogurt-pitny', 'Pitný jogurt a kysané nápoje', P, 'Mléčné výrobky', 'l', 'druh kysaného mléčného nápoje', [
    ['Pitný jogurt', 'tekutý jogurt k pití, bílý i ochucený'],
    ['Acidofilní mléko', 'kysané mléko s acidofilní kulturou'],
    ['Podmáslí', 'podmáslí přírodní nebo ochucené'],
    ['Ayran a lassi', 'solený ayran, lassi'],
    ['Probiotický nápoj', 'mléčný nápoj s kulturami typu Lactobacillus casei', 'kefír, který je vlastním typem'],
  ]),
  nw('skyr-proteinove-mlecne', 'Skyr a proteinové mléčné výrobky', P, 'Mléčné výrobky', 'kg', 'typ výrobku', [
    ['Skyr', 'islandský typ kysaného mléčného výrobku s vysokým obsahem bílkovin'],
    ['Proteinový jogurt', 'jogurt s deklarovaným zvýšeným obsahem bílkovin'],
    ['Proteinový pudink', 'chlazený pudink s deklarovaným zvýšeným obsahem bílkovin'],
  ]),
  nw('mlecne-dezerty', 'Mléčné dezerty', P, 'Mléčné výrobky', 'kg', 'druh dezertu', [
    ['Chlazený pudink', 'hotový mléčný pudink v kelímku'],
    ['Mléčná rýže', 'hotová mléčná rýže v kelímku'],
    ['Tvarohový dezert', 'sladký dezert z tvarohu v kelímku', 'čistý tvaroh'],
    ['Krémový dezert', 'smetanové a čokoládové krémy, mousse, panna cotta'],
    ['Mléčný řez', 'mléčný řez a podobné chlazené pečivové dezerty'],
  ]),
  nw('smetanovy-syr', 'Čerstvý sýr a smetanový sýr', P, 'Mléčné výrobky', 'kg', 'druh čerstvého sýra', [
    ['Smetanový sýr', 'cream cheese, přírodní nebo ochucený'],
    ['Ricotta', 'ricotta'],
    ['Mascarpone', 'mascarpone'],
    ['Žervé', 'žervé a čerstvý sýr typu žervé'],
    ['Čerstvý sýr zrnitý nebo pomazánkový', 'čerstvý sýr, který není ricotta, mascarpone ani cottage', 'cottage cheese, který je vlastním typem'],
  ]),
  ex('hermelin', 'Hermelín a camembert', P, 'Mléčné výrobky', 'kg', 'druh sýra s bílou plísní', [
    ['Hermelín', 'sýr s bílou plísní typu hermelín'],
    ['Camembert', 'camembert'],
    ['Brie', 'brie'],
    ['Sýr s bílou plísní', 'jiný sýr s bílou plísní na povrchu, který není hermelín, camembert ani brie'],
  ]),
  ex('niva', 'Niva', P, 'Mléčné výrobky', 'kg', 'druh sýra s modrou plísní', [
    ['Niva', 'český sýr s modrou plísní typu niva'],
    ['Gorgonzola', 'gorgonzola'],
    ['Roquefort', 'roquefort'],
    ['Stilton a Danablu', 'stilton, danablu a příbuzné sýry s modrou plísní'],
  ]),
  ex('mozzarella', 'Mozzarella', P, 'Mléčné výrobky', 'kg', 'forma mozzarelly', [
    ['Kulatá mozzarella v nálevu', 'kulička v nálevu, ball, cherry, bocconcini'],
    ['Strouhaná mozzarella', 'strouhaná nebo plátkovaná mozzarella na pizzu a zapékání'],
    ['Burrata', 'burrata'],
    ['Uzená mozzarella', 'mozzarella uzená nebo grilovaná'],
  ]),
  nw('syr-tvrdy-poloztvrdy', 'Sýr tvrdý a polotvrdý (ostatní druhy)', P, 'Mléčné výrobky', 'kg', 'jméno druhu sýra', [
    ['Ementál', 'ementál, ementálský typ s oky'],
    ['Čedar', 'čedar, cheddar'],
    ['Maasdam', 'maasdam a maasdamský typ'],
    ['Gruyère a Comté', 'gruyère, comté, alpské tvrdé sýry'],
    ['Trapistický sýr', 'trapist a trapistický typ'],
    ['Uzený sýr', 'sýr přírodní uzený, cihla nebo plátky'],
    ['Sýr na gril', 'halloumi, grilovací sýr'],
    ['Tvarůžky', 'olomoucké tvarůžky a zrající sýry ve vlastní plísni'],
  ]),
  nw('syr-strouhany-platkovany', 'Sýr strouhaný a plátkový', P, 'Mléčné výrobky', 'kg', 'forma úpravy sýra', [
    ['Strouhaný sýr', 'sýr strouhaný, směs pro zapékání'],
    ['Plátkový sýr', 'sýr plátkovaný, přírodní, sendvičové plátky'],
    ['Sýr v kostičkách', 'kostičky sýra, sýr na salát'],
  ]),
  ex('kefir', 'Kefír', P, 'Mléčné výrobky', 'kg', 'druh kefíru', [
    ['Bílý kefír', 'kefír přírodní bez příchuti'],
    ['Ochucený kefír', 'kefír s ovocem nebo příchutí'],
    ['Kozí kefír', 'kefír z kozího mléka'],
  ]),
  nw('mleko-kozi-ovci', 'Kozí a ovčí mléko', P, 'Mléčné výrobky', 'l', 'druh zvířete', [
    ['Kozí mléko', 'kozí mléko, čerstvé nebo trvanlivé'],
    ['Ovčí mléko', 'ovčí mléko'],
  ]),
  nw('mleko-zahustene-susene', 'Zahuštěné a sušené mléko', P, 'Mléčné výrobky', 'kg', 'forma mléčného koncentrátu', [
    ['Slazené kondenzované mléko', 'kondenzované mléko slazené, karamelizované'],
    ['Neslazené zahuštěné mléko', 'zahuštěné mléko neslazené, k přidání do kávy'],
    ['Sušené plnotučné mléko', 'plnotučné sušené mléko'],
    ['Sušené odtučněné mléko', 'sušené odtučněné mléko, sušená syrovátka'],
    ['Kávová smetanka', 'sušená či tekutá smetanka do kávy v kapslích a porcích'],
  ]),
  ex('vejce', 'Vejce', P, 'Vejce', 'ks', 'způsob chovu a druh vejce', [
    ['Vejce z podestýlky', 'vejce z chovu na podestýlce, kód 2'],
    ['Vejce z volného výběhu', 'vejce z volného výběhu, kód 1'],
    ['Bio vejce', 'vejce z ekologického chovu, kód 0'],
    ['Vejce z klece', 'vejce z klecového chovu, kód 3'],
    ['Křepelčí vejce', 'křepelčí vejce', 'slepičí vejce'],
    ['Vařená vejce', 'předvařená vejce, barvená vejce', 'syrová vejce'],
  ]),

  // --- Pečivo -----------------------------------------------------------------------------------------
  ex('chleb', 'Chléb', P, 'Pečivo', 'kg', 'hlavní obilovina nebo způsob přípravy chleba', [
    ['Pšenično-žitný chléb', 'chléb s oběma obilovinami, kmínový, konzumní'],
    ['Žitný chléb', 'chléb převážně z žitné mouky'],
    ['Kváskový chléb', 'chléb připravený kváskem'],
    ['Celozrnný chléb', 'chléb z celozrnné mouky'],
    ['Vícezrnný chléb', 'chléb se semínky a zrny, vícezrnný'],
    ['Bezlepkový chléb', 'chléb s označením bez lepku'],
    ['Chléb s vlákninou nebo proteinem', 'chléb s přidanou vlákninou nebo bílkovinou'],
  ]),
  nw('pecivo-sladke', 'Sladké pečivo', P, 'Pečivo', 'ks', 'druh těsta a náplně', [
    ['Croissant', 'croissant, máslový, čokoládový'],
    ['Koláč', 'koláč, koláč s tvarohem, mákem, povidly'],
    ['Buchta', 'buchta, buchta s náplní, bublanina'],
    ['Šneček a hotový závin', 'šnek, štrúdl, závin z listového těsta'],
    ['Donut a kobliha', 'koblihy, donuty, kobliha s marmeládou'],
    ['Muffin a cupcake', 'muffin, cupcake'],
    ['Vánočka a mazanec', 'vánočka, mazanec, sváteční pečivo kynuté'],
    ['Chlazený dort a zákusek', 'chlazené dorty a zákusky z cukrářské vitríny', 'balené trvanlivé sušenky a řezy'],
  ]),
  nw('pecivo-slane', 'Slané pečivo', P, 'Pečivo', 'ks', 'druh slaného pečiva', [
    ['Pletýnka a slaná tyčinka', 'slané tyčinky, pletýnky, kmínky'],
    ['Slané plněné pečivo', 'pečivo s náplní sýr, šunka, uzenina'],
    ['Slaný rohlík', 'rohlíky s posypem, sýrové, solné'],
    ['Plněná bageta', 'hotová plněná bageta a slaný sendvičový výrobek'],
    ['Tortilla a placka', 'tortilly, pita, naan, wrap'],
    ['Bramborák a lívanec', 'bramboráky a lívance hotové k ohřevu'],
  ]),
  nw('pecivo-trvanlive', 'Trvanlivé pečivo', P, 'Pečivo', 'kg', 'druh trvanlivého pečiva', [
    ['Strouhanka', 'strouhanka z pečiva, drcená houska'],
    ['Suchary a krutony', 'suchary, přípitky, krutony'],
    ['Křehký chléb', 'knäckebrot, křehké plátky, rýžové chlebíčky'],
    ['Piškoty a dortové korpusy', 'piškoty, hotové korpusy, babiččiny piškoty'],
    ['Oplatky', 'oplatky, ledové kaštany, oplatky lázeňské'],
    ['Trvanlivé toustové pečivo', 'trvanlivý toustový chléb, bagety'],
  ]),
  ex('rohlik', 'Rohlík', P, 'Pečivo', 'ks', 'druh rohlíku', [
    ['Bílý rohlík', 'klasický pšeničný rohlík'],
    ['Celozrnný rohlík', 'rohlík z celozrnné mouky'],
    ['Houskový rohlík', 'rohlík houskový, grahamový'],
  ]),
  nw('burgerove-bulky', 'Bulky na hamburger a hot dog', P, 'Pečivo', 'ks', 'účel bulky', [
    ['Hamburgerová bulka', 'bulka na burger, sezamová'],
    ['Párkovka', 'hot dog rohlík, párkovka, brioška'],
    ['Toustová žemle', 'žemle na sendvič, ciabatta, focaccia'],
  ]),

  // --- Maso a uzeniny -----------------------------------------------------------------------------------
  nw('hovezi-maso-druhy', 'Hovězí maso čerstvé (ostatní části)', P, 'Maso a uzeniny', 'kg', 'anatomická část', [
    ['Hovězí roštěná', 'roštěná, ribeye, entrecôte'],
    ['Hovězí líčka', 'hovězí líčka, ocas, hovězí kližka'],
    ['Hovězí žebra', 'hovězí žebra, short ribs'],
    ['Hovězí maso na vývar', 'hovězí kosti, hrudí, nožka na vývar'],
  ]),
  nw('kralik-kachna-husa', 'Králík, kachna, husa a zvěřina', P, 'Maso a uzeniny', 'kg', 'druh zvířete', [
    ['Králičí maso', 'králík celý, králičí stehna, hřbet'],
    ['Kachní maso', 'kachna celá, kachní prsa, kachní stehna'],
    ['Husí maso', 'husa celá, husí stehna, husí prsa'],
    ['Jehněčí maso', 'jehněčí kýta, hřbet, kotlety'],
    ['Zvěřina', 'srnčí, jelení, divočák a jiná lovná zvěř'],
  ]),
  nw('uzeniny-trvanlive', 'Trvanlivé uzeniny', P, 'Maso a uzeniny', 'kg', 'druh uzeniny', [
    ['Salám', 'salám vysočina, herkules, uherský, ementálský'],
    ['Klobása a špekáček', 'špekáčky, klobásy, opékací uzeniny'],
    ['Šunkový salám', 'šunkový salám, lunchmeat, mortadela'],
    ['Paštika', 'jemná a hrubá paštika, játrová paštika'],
    ['Tlačenka a jelito', 'tlačenka, jelito, jitrnice'],
    ['Uzený bok a špek', 'uzený bok, špek, anglická slanina v balení', 'slanina plátkovaná, která je vlastním typem'],
    ['Sušené maso a jerky', 'sušená šunka, sušené maso, jerky'],
  ]),
  ex('sunka', 'Šunka', P, 'Maso a uzeniny', 'kg', 'druh šunky', [
    ['Šunka vepřová', 'vepřová šunka, šunka od kosti'],
    ['Šunka drůbeží', 'kuřecí a krůtí šunka'],
    ['Šunka hovězí nebo jiná', 'šunka z hovězího masa'],
    ['Parmská a sušená šunka', 'parma, prosciutto, serrano, sušená šunka'],
  ]),
  ex('parky', 'Párky', P, 'Maso a uzeniny', 'kg', 'druh párků', [
    ['Vepřové párky', 'párky vepřové'],
    ['Drůbeží párky', 'kuřecí a krůtí párky'],
    ['Vídeňské párky', 'vídeňské, hovězí, jemné párky'],
    ['Sýrové párky', 'párky s přidaným sýrem'],
  ]),
  nw('maso-polotovary', 'Maso a drůbež, hotové polotovary', P, 'Maso a uzeniny', 'kg', 'forma úpravy', [
    ['Marinované maso', 'marinované maso na gril, marinované steaky a špízy'],
    ['Řízek a plněný řízek', 'řízky, plněné, obalované k smažení'],
    ['Špíz', 'špízy, jehly, nabodávané maso'],
    ['Sekaná a karbanátek', 'hotová sekaná, karbanátky, masové kuličky'],
    ['Burger maso', 'masová placka na burger, formované maso'],
  ]),

  // --- Ryby a mořské plody ---------------------------------------------------------------------------------
  ex('losos', 'Losos', P, 'Ryby a mořské plody', 'kg', 'forma lososa', [
    ['Lososový filet čerstvý', 'losos čerstvý, filet, steak'],
    ['Uzený losos', 'losos uzený, plátky'],
    ['Lososové steaky mražené', 'mražený losos, filet'],
    ['Lososové kostky pro sushi', 'losos určený k syrové konzumaci'],
  ]),
  nw('ryby-cerstve', 'Ryby čerstvé a chlazené', P, 'Ryby a mořské plody', 'kg', 'druh ryby', [
    ['Pstruh', 'pstruh duhový, filet, celý'],
    ['Kapr', 'kapr celý, porce, filet'],
    ['Treska a mintaj', 'treska, mintaj, filet z tresky'],
    ['Sleď a makrela', 'sleď, makrela čerstvá nebo uzená'],
    ['Platýs a mořský jazyk', 'platýs, solea, mořský jazyk'],
    ['Pangas a tilápie', 'pangas, tilápie, filé z chovu'],
    ['Candát a štika', 'candát, štika, sumec, kapr'],
  ]),
  nw('morske-plody', 'Mořské plody', P, 'Ryby a mořské plody', 'kg', 'druh mořského plodu', [
    ['Krevety', 'krevety loupané i neloupané, vařené i syrové'],
    ['Chobotnice a kalamáry', 'chobotnice, sépie, kalamáry'],
    ['Mušle a hřebenatky', 'mušle, slávky, hřebenatky'],
    ['Krabí tyčinky a surimi', 'krabí tyčinky, surimi'],
    ['Humr a krab', 'humr, langusta, krab'],
  ]),
  nw('ryby-konzervovane-solene', 'Ryby uzené, solené a marinované', P, 'Ryby a mořské plody', 'kg', 'způsob konzervace', [
    ['Uzená ryba', 'uzená makrela, pstruh, sleď'],
    ['Marinovaný sleď', 'sleď v nálevu, rollmops, matjes'],
    ['Solená ryba', 'solený sleď, solená treska'],
    ['Rybí lahůdka', 'rybí pomazánka, kaviár, ikry', 'konzervované ryby v plechovce'],
  ]),

  // --- Ovoce a zelenina ---------------------------------------------------------------------------------------
  nw('ovoce-citrusove', 'Citrusové plody (ostatní)', P, 'Ovoce a zelenina', 'kg', 'druh citrusu', [
    ['Pomeranče', 'pomeranč, krvavý pomeranč, navel'],
    ['Grapefruity', 'grapefruit bílý a červený'],
    ['Limetky', 'limetky'],
    ['Pomelo', 'pomelo, jiné velké citrusy'],
  ]),
  nw('ovoce-peckove-jadernate', 'Peckoviny a jádroviny (sezónní)', P, 'Ovoce a zelenina', 'kg', 'druh ovoce', [
    ['Broskve a nektarinky', 'broskve, nektarinky, plochá broskev'],
    ['Švestky a slívy', 'švestky, slívy, mirabelky, renklódy'],
    ['Třešně a višně', 'třešně, višně'],
    ['Meruňky', 'meruňky'],
    ['Kdoule a mišpule', 'kdoule, mišpule, jeřabiny'],
  ]),
  nw('ovoce-exoticke', 'Exotické ovoce', P, 'Ovoce a zelenina', 'kg', 'druh ovoce', [
    ['Ananas', 'ananas celý, krájený'],
    ['Mango', 'mango zralé'],
    ['Kiwi', 'kiwi zelené, zlaté'],
    ['Papája a liči', 'papája, liči, rambutan'],
    ['Datle a fíky', 'čerstvé datle, fíky, kaki'],
    ['Granátové jablko', 'granátové jablko'],
    ['Meloun', 'vodní meloun, cukrový, galia'],
    ['Maracuja a dračí ovoce', 'maracuja, pitahaya, dračí ovoce'],
  ]),
  nw('ovoce-lesni-drobne', 'Drobné ovoce (ostatní)', P, 'Ovoce a zelenina', 'kg', 'druh drobného ovoce', [
    ['Ostružiny', 'ostružiny'],
    ['Rybíz a angrešt', 'rybíz červený, černý, angrešt'],
    ['Brusinky', 'brusinky, klikva'],
    ['Lesní směs čerstvá', 'čerstvá směs lesního ovoce'],
  ]),
  nw('zelenina-listova', 'Listová zelenina a salát', P, 'Ovoce a zelenina', 'kg', 'druh listové zeleniny', [
    ['Hlávkový salát', 'hlávkový, ledový, římský salát'],
    ['Rukola a polníček', 'rukola, polníček, listy špenátu na salát'],
    ['Špenát', 'čerstvý špenát, baby špenát'],
    ['Směs salátů', 'baby leaf, směs listových salátů, balená'],
    ['Čínské zelí a pak choi', 'čínské zelí, pak choi, kapusta'],
    ['Mangold a kadeřávek', 'mangold, kadeřávek, černý kapusta'],
  ]),
  nw('zelenina-korenova', 'Kořenová zelenina (ostatní)', P, 'Ovoce a zelenina', 'kg', 'druh kořenové zeleniny', [
    ['Petržel a pastinák', 'petržel kořen, pastinák'],
    ['Červená řepa', 'červená řepa, vařená, čerstvá'],
    ['Ředkvičky a ředkev', 'ředkvičky, černá ředkev, daikon'],
    ['Křen a zázvor', 'křen, zázvor čerstvý, kurkuma čerstvá'],
    ['Batáty', 'batáty, sladké brambory'],
    ['Kedlubna a tuřín', 'kedlubna, tuřín, vodnice'],
  ]),
  ex('brambory', 'Brambory', P, 'Ovoce a zelenina', 'kg', 'varný typ bramboru', [
    ['Brambory salátové', 'varný typ A, pevné, salát'],
    ['Brambory univerzální', 'varný typ B, polopevné'],
    ['Brambory moučné', 'varný typ C, na kaši a knedlíky'],
    ['Nové brambory', 'rané brambory, nové'],
    ['Brambory k pečení', 'velké brambory na pečení, baked potato'],
  ]),
  ex('cibule', 'Cibule', P, 'Ovoce a zelenina', 'kg', 'druh cibule', [
    ['Cibule žlutá', 'běžná kuchyňská cibule'],
    ['Cibule červená', 'červená cibule, šalotka'],
    ['Jarní cibulka', 'jarní cibulka, pórek, pažitka čerstvá'],
    ['Cibule bílá', 'bílá cibule, perlová cibulka'],
  ]),
  ex('rajcata', 'Rajčata', P, 'Ovoce a zelenina', 'kg', 'typ rajčete', [
    ['Rajčata keříková', 'rajčata na větvičce, keříková'],
    ['Rajčata cherry', 'cherry, koktejlová, datlová rajčátka'],
    ['Rajčata masová', 'masová rajčata, hovězí srdce'],
    ['Rajčata kulatá', 'běžná kulatá rajčata'],
  ]),
  ex('paprika', 'Paprika', P, 'Ovoce a zelenina', 'kg', 'barva nebo odrůda papriky', [
    ['Paprika červená', 'červená paprika'],
    ['Paprika žlutá', 'žlutá paprika'],
    ['Paprika zelená', 'zelená paprika'],
    ['Paprika špičatá', 'špičatá paprika, kapie'],
    ['Chilli papričky čerstvé', 'čerstvé chilli, jalapeño'],
  ]),
  nw('zelenina-ostatni-cerstva', 'Zelenina čerstvá (ostatní druhy)', P, 'Ovoce a zelenina', 'kg', 'druh zeleniny', [
    ['Lilek', 'lilek, baklažán'],
    ['Dýně', 'dýně hokkaido, máslová dýně, tykev'],
    ['Květák', 'květák, romanesco'],
    ['Zelí hlávkové', 'bílé a červené zelí, kysané zelí čerstvé'],
    ['Kukuřice', 'kukuřičné klasy čerstvé'],
    ['Hrášek a fazolové lusky', 'čerstvý hrášek, fazolky, lusky'],
    ['Chřest', 'zelený a bílý chřest'],
    ['Fenykl a celer řapíkatý', 'fenykl, celer řapíkatý'],
    ['Klíčky a mikrozelenina', 'klíčky, hrachové výhonky, mikrobylinky'],
  ]),
  nw('bylinky-cerstve', 'Čerstvé bylinky', P, 'Ovoce a zelenina', 'ks', 'druh bylinky', [
    ['Bazalka', 'čerstvá bazalka v květináči nebo svazku'],
    ['Petržel natě', 'čerstvá petrželová nať'],
    ['Pažitka a kopr', 'čerstvá pažitka, kopr'],
    ['Máta a meduňka', 'čerstvá máta, meduňka'],
    ['Tymián a rozmarýn', 'čerstvý tymián, rozmarýn, šalvěj, oregano'],
  ]),
  ex('houby', 'Houby', P, 'Ovoce a zelenina', 'kg', 'druh houby', [
    ['Žampiony', 'žampiony bílé a hnědé'],
    ['Hlíva ústřičná', 'hlíva ústřičná'],
    ['Shiitake a další', 'shiitake, enoki, eryngii'],
    ['Lesní houby čerstvé', 'hřiby, kozáky, lišky, bedly'],
    ['Sušené houby', 'sušené lesní houby, hřiby sušené', 'čerstvé houby'],
  ]),
  nw('ovoce-susene-cerstve-baleni', 'Hotová zelenina a ovoce k okamžité konzumaci', P, 'Ovoce a zelenina', 'kg', 'forma úpravy', [
    ['Krájené ovoce', 'krájené ovoce v misce, ovocný salát'],
    ['Zeleninová mísa', 'krájená zelenina na salát, tzv. salátový mix'],
    ['Zeleninový snack', 'baby mrkev, snack zelenina'],
    ['Smoothie a čerstvě lisovaná šťáva', 'čerstvě lisovaný džus a smoothie v chladničce', 'trvanlivé džusy'],
  ]),
]
