// Seed proposal — Potraviny, shelf-stable goods: pantry, baking, sauces, snacks, sweets, drinks, frozen.
import { existingType as ex, newType as nw, type SeedType } from './types'

const P = 'Potraviny' as const

export const POTRAVINY_TRVANLIVE: SeedType[] = [
  // --- Těstoviny a rýže, luštěniny, obiloviny -------------------------------------------------------------
  nw('nudle-asijske', 'Nudle a těstoviny asijské', P, 'Těstoviny a rýže', 'kg', 'druh nudlí', [
    ['Rýžové nudle', 'rýžové nudle, vermicelli'],
    ['Vaječné nudle', 'čínské vaječné nudle, mie'],
    ['Udon', 'udon'],
    ['Soba', 'soba, pohankové nudle'],
    ['Skleněné nudle', 'skleněné nudle ze škrobu'],
  ]),
  nw('kuskus-bulgur', 'Kuskus, bulgur a další obiloviny', P, 'Těstoviny a rýže', 'kg', 'druh obiloviny', [
    ['Kuskus', 'kuskus'],
    ['Bulgur', 'bulgur'],
    ['Quinoa', 'quinoa, merlík čílský'],
    ['Pohanka', 'pohanka loupaná, kroupy pohankové'],
    ['Jáhly', 'jáhly, proso'],
    ['Ječné kroupy', 'kroupy, ječmen, pšeničná kaše'],
    ['Polenta a krupice', 'kukuřičná krupice, polenta, pšeničná krupice'],
    ['Amarant a špalda', 'amarant, špalda loupaná, ovesné kroupy'],
  ]),
  nw('lusteniny', 'Luštěniny', P, 'Luštěniny', 'kg', 'druh luštěniny', [
    ['Čočka', 'čočka červená, zelená, hnědá'],
    ['Cizrna', 'cizrna suchá'],
    ['Fazole', 'fazole bílé, červené, černé, adzuki'],
    ['Hrách', 'hrách půlený, žlutý, zelený'],
    ['Sójové boby', 'suché sójové boby, mungo'],
    ['Lupina', 'lupina, bob'],
  ]),
  nw('lusteniny-konzervovane', 'Luštěniny konzervované', P, 'Konzervy', 'kg', 'druh luštěniny', [
    ['Fazole v konzervě', 'fazole červené, bílé, ve slaném nálevu'],
    ['Cizrna v konzervě', 'cizrna z konzervy'],
    ['Čočka v konzervě', 'čočka vařená, v konzervě nebo sklenici'],
    ['Hrášek a kukuřice v konzervě', 'hrášek, kukuřice ve slaném nálevu'],
  ]),
  nw('zelenina-konzervovana', 'Zelenina konzervovaná a sterilovaná', P, 'Konzervy', 'kg', 'druh zeleniny', [
    ['Rajčata v konzervě', 'loupaná, krájená, drcená rajčata, pasírovaná rajčata'],
    ['Sterilované okurky', 'sterilovaná okurka, nakládaná, kyselé'],
    ['Zelí a červená řepa', 'sterilované zelí, červená řepa'],
    ['Kukuřice sterilovaná', 'sterilovaná kukuřice, kukuřice v konzervě'],
    ['Houby sterilované', 'houby sterilované, žampiony v nálevu'],
    ['Paprika a ostatní', 'paprika sterilovaná, lečo, ratatouille'],
  ]),
  nw('ovoce-konzervovane', 'Ovoce konzervované a kompoty', P, 'Konzervy', 'kg', 'druh ovoce', [
    ['Kompot broskvový', 'kompot z broskví'],
    ['Kompot ananasový', 'ananas v konzervě'],
    ['Kompot ze smíšeného ovoce', 'ovocný koktejl, kompoty směsné'],
    ['Švestkový kompot', 'kompot ze švestek, třešní, višní'],
    ['Mandarinky v konzervě', 'mandarinky v nálevu'],
  ]),
  nw('masa-konzervovana', 'Masové a rybí konzervy', P, 'Konzervy', 'kg', 'druh konzervy', [
    ['Sardinky v oleji', 'sardinky, ančovičky v oleji'],
    ['Makrela v konzervě', 'makrela v konzervě'],
    ['Pomazánka z ryb', 'rybí pomazánky'],
    ['Masová konzerva', 'tlačenka v konzervě, pražská šunka, masové kostky'],
    ['Hotové jídlo v konzervě', 'gulášová, fazolová konzerva, mexický chilli'],
    ['Polévka v konzervě', 'konzervovaná polévka'],
  ]),

  // --- Mouka a pečení -------------------------------------------------------------------------------------------
  ex('mouka', 'Mouka', P, 'Mouka a pečení', 'kg', 'obilovina nebo speciální účel mouky', [
    ['Žitná mouka', 'chlebová mouka žitná, celozrnná žitná'],
    ['Špaldová mouka', 'špaldová mouka světlá, celozrnná'],
    ['Celozrnná pšeničná mouka', 'celozrnná pšeničná mouka'],
    ['Mouka na chleba', 'směs a speciální mouka pro chleba'],
    ['Bezlepková mouka', 'směs bezlepkových mouk, rýžová, kukuřičná'],
    ['Mouka na pizzu', 'pizza mouka typu 00'],
    ['Instantní mouka', 'instantní mouka, kypřící'],
  ]),
  nw('peceni-ingredience', 'Pečení — kypřidla a příchutě', P, 'Mouka a pečení', 'kg', 'funkce přísady', [
    ['Prášek do pečiva', 'kypřicí prášek'],
    ['Jedlá soda', 'jedlá soda, hydrogenuhličitan'],
    ['Vanilkový cukr', 'vanilkový cukr, vanilkový extrakt'],
    ['Želatina a zahušťovadla', 'želatina, agar, škrob na zahuštění'],
    ['Kvasnice', 'sušené kvasnice, čerstvé droždí'],
    ['Aroma na pečení', 'rumové, citronové, mandlové aroma'],
    ['Čokoláda na vaření', 'čokoláda na vaření, kuvertura, kapky'],
    ['Posypy a zdobení', 'cukrářské posypy, barvy, glazury'],
  ]),
  nw('smesi-na-peceni', 'Směsi a polotovary na pečení', P, 'Mouka a pečení', 'kg', 'hotový výrobek ze směsi', [
    ['Směs na bábovku a koláč', 'směs na bábovku, dort, koláč'],
    ['Směs na palačinky', 'palačinkové a lívanečkové těsto v prášku'],
    ['Pudinkový prášek', 'pudink v prášku, krémový prášek'],
    ['Těsto listové a křehké', 'chlazené listové těsto, křehké těsto, těsto na pizzu'],
    ['Knedlíky v prášku', 'směs na knedlíky, bramborová kaše v prášku'],
    ['Strouhanka', 'strouhanka, obalovací směs'],
  ]),
  ex('cukr-krupice', 'Cukr krupice', P, 'Mouka a pečení', 'kg', 'forma cukru', [
    ['Cukr krystal', 'bílý krystal cukr'],
    ['Cukr třtinový', 'hnědý třtinový cukr, muscovado'],
    ['Cukr želírující', 'cukr na zavařování, želírující cukr'],
    ['Kostkový cukr', 'cukr kostka'],
  ]),
  nw('sladidla-sirupy', 'Sladidla a sirupy', P, 'Mouka a pečení', 'kg', 'druh sladidla', [
    ['Javorový sirup', 'javorový sirup'],
    ['Agávový sirup', 'agávový sirup'],
    ['Datlový a rýžový sirup', 'datlový sirup, rýžový sirup'],
    ['Erythritol a xylitol', 'cukrové alkoholy ve formě sypkého sladidla'],
    ['Stévie', 'sladidla na bázi stévie'],
    ['Umělá sladidla', 'tablety a tekutá sladidla s aspartamem, sukralózou apod.'],
  ]),
  nw('likery', 'Likéry', P, 'Alkoholické nápoje', 'l', 'základní příchuť likéru', [
    ['Krémový likér', 'smetanové a vaječné likéry'],
    ['Ovocný likér', 'ovocné likéry, višňový, pomerančový'],
    ['Bylinný likér', 'bylinné a hořké likéry'],
    ['Ořechový a kávový likér', 'likéry z ořechů nebo kávy'],
  ]),

  // --- Oleje a tuky -------------------------------------------------------------------------------------------------
  ex('olej', 'Olej', P, 'Oleje a tuky', 'l', 'rostlinný zdroj a úprava oleje', [
    ['Sójový olej', 'sójový olej'],
    ['Kokosový olej', 'kokosový olej, kokosový tuk'],
    ['Sezamový olej', 'sezamový olej'],
    ['Arašídový olej', 'arašídový olej'],
    ['Lněný olej', 'lněný, dýňový, makový olej lisovaný za studena'],
    ['Olej ve spreji', 'olej ve spreji na pečení a smažení'],
  ]),
  nw('margarin-tuky', 'Margaríny a rostlinné tuky', P, 'Oleje a tuky', 'kg', 'určení tuku', [
    ['Margarín na mazání', 'margarín, rostlinný tuk na pečivo'],
    ['Margarín na pečení', 'tuk na pečení, hera, ztužený tuk'],
    ['Sádlo', 'vepřové sádlo, husí sádlo'],
    ['Rostlinné máslo', 'rostlinný výrobek podobný másla'],
    ['Smažicí tuk', 'tuk na fritování a smažení'],
  ]),
  nw('ocet-dochucovani', 'Ocet a kyselé dochucovadlo', P, 'Omáčky a dochucovadla', 'l', 'druh octa', [
    ['Ocet kvasný', 'kvasný lihový ocet'],
    ['Jablečný ocet', 'ocet jablečný'],
    ['Vinný ocet', 'bílý a červený vinný ocet'],
    ['Balsamico', 'balsamikový ocet, krém'],
    ['Rýžový ocet', 'rýžový ocet, sushi ocet'],
    ['Citronová šťáva', 'citronová šťáva, limetková šťáva v lahvičce'],
  ]),

  // --- Omáčky a dochucovadla -------------------------------------------------------------------------------------------
  ex('kecup', 'Kečup', P, 'Omáčky a dochucovadla', 'kg', 'chuťový profil kečupu', [
    ['Kečup jemný', 'jemný nebo dětský kečup'],
    ['Kečup pálivý', 'pálivý nebo ostrý kečup'],
    ['Kečup bez cukru', 'kečup se sníženým obsahem cukru nebo bez cukru'],
    ['Kečup se sladidly', 'kečup s přírodními sladidly'],
    ['Curry kečup', 'kečup s kari a speciální příchutí'],
  ]),
  ex('horcice', 'Hořčice', P, 'Omáčky a dochucovadla', 'kg', 'typ hořčice', [
    ['Hořčice plnotučná', 'plnotučná hořčice'],
    ['Hořčice kremžská', 'kremžská hořčice'],
    ['Hořčice dijonská', 'dijonská hořčice'],
    ['Hořčice sladká', 'bavorská, sladká hořčice'],
    ['Hořčice pálivá', 'pálivá, ostrá hořčice'],
    ['Hořčice ve spreji', 'hořčice ve tubě nebo spreji'],
  ]),
  ex('majoneza', 'Majonéza', P, 'Omáčky a dochucovadla', 'kg', 'typ majonézy', [
    ['Majonéza klasická', 'majonéza plnotučná, vaječná'],
    ['Majonéza lehká', 'majonéza se sníženým obsahem tuku'],
    ['Tatarská omáčka', 'tatarská omáčka, tatarka'],
    ['Dresink', 'dresingy na salát, caesar, vinaigrette'],
    ['Veganská majonéza', 'majonéza bez vajec'],
  ]),
  nw('omacky-hotove', 'Hotové omáčky', P, 'Omáčky a dochucovadla', 'kg', 'druh omáčky', [
    ['Rajčatová omáčka', 'omáčka na těstoviny, arrabbiata, bolognese hotová'],
    ['Smetanová omáčka', 'omáčka carbonara, alfredo, bílé omáčky'],
    ['Pesto', 'pesto bazalkové, rajčatové, rukolové'],
    ['Asijská omáčka', 'sójová, sladkokyselá, teriyaki, ústřicová'],
    ['Grilovací omáčka', 'BBQ omáčka, steaková, marinády'],
    ['Pálivá omáčka', 'sriracha, tabasco, sambal, chilli omáčka'],
    ['Zálivka na salát', 'dresink, zálivky, olej a ocet s kořením'],
    ['Omáčka k masu', 'svíčková, houbová, koprovka hotová'],
    ['Pomazánková základna', 'hummus, tzatziki, guacamole hotové'],
  ]),
  nw('vyvary-bujony', 'Vývary a bujóny', P, 'Omáčky a dochucovadla', 'kg', 'forma vývaru', [
    ['Bujón kostky', 'kostky bujónové, prášek vývarový'],
    ['Tekutý vývar', 'hotový vývar v krabici, koncentrovaný tekutý vývar'],
    ['Vegeta a dochucovadlo', 'univerzální dochucovadlo na bázi sušené zeleniny'],
    ['Instantní polévka', 'polévky v prášku, polévky v kelímku'],
  ]),
  ex('sul', 'Sůl', P, 'Koření a bylinky', 'kg', 'druh soli', [
    ['Sůl jedlá jodidovaná', 'běžná jedlá sůl, jodidovaná'],
    ['Sůl mořská', 'mořská sůl, jemná i hrubá'],
    ['Sůl himálajská', 'růžová himálajská sůl'],
    ['Sůl s příchutí', 'česneková, bylinková, uzená sůl'],
    ['Sůl na ubrousky', 'solící směsi, solnička'],
  ]),
  nw('koreni', 'Koření a koření směsi', P, 'Koření a bylinky', 'kg', 'forma koření', [
    ['Pepř', 'pepř černý, bílý, růžový, celý i mletý'],
    ['Paprika mletá', 'sladká, pálivá, uzená mletá paprika'],
    ['Bylinky sušené', 'majoránka, oregano, bazalka, tymián, petržel sušená'],
    ['Směs koření', 'koření na gulášové, kuřecí, hovězí, grilovací'],
    ['Kari a orientální koření', 'kari, kurkuma, garam masala, kmín římský'],
    ['Skořice a sladké koření', 'skořice, hřebíček, badyán, zázvor mletý, vanilkové lusky'],
    ['Česnek a cibule sušené', 'sušený česnek, granulovaná cibule'],
    ['Kmín a bobkový list', 'kmín, bobkový list, nové koření, jalovec'],
  ]),

  // --- Snídaně, sladké a sladkosti ----------------------------------------------------------------------------------
  ex('cerealie', 'Cereálie', P, 'Cereálie a snídaně', 'kg', 'forma cereálií', [
    ['Müsli', 'müsli, granola'],
    ['Kukuřičné lupínky', 'corn flakes, kukuřičné lupínky'],
    ['Čokoládové cereálie', 'cereálie s čokoládou, polštářky'],
    ['Cereální tyčinky', 'müsli a cereální tyčinky'],
    ['Slepené cereálie', 'pufované cereálie, rýžové křupky'],
    ['Celozrnné cereálie', 'cereálie celozrnné, otruby, vláknina'],
  ]),
  ex('ovesne-vlocky', 'Ovesné vločky', P, 'Cereálie a snídaně', 'kg', 'zpracování vloček', [
    ['Vločky jemné', 'jemné ovesné vločky, instantní'],
    ['Vločky hrubé', 'hrubé ovesné vločky'],
    ['Vločky z jiných obilovin', 'žitné, špaldové, pšeničné, ječné vločky'],
    ['Instantní kaše', 'instantní ovesná kaše, porridge v sáčku'],
  ]),
  ex('kakao', 'Kakao', P, 'Káva a čaj', 'kg', 'forma kakaa', [
    ['Kakao prášek', 'holandské nebo běžné kakao v prášku'],
    ['Instantní kakaový nápoj', 'rozpustné kakao s cukrem'],
    ['Horká čokoláda', 'horká čokoláda v prášku nebo tabulce'],
    ['Kakaové boby', 'kakaové boby, nibs'],
  ]),
  ex('med', 'Med', P, 'Džemy, med a pomazánky', 'kg', 'původ medu', [
    ['Med květový', 'květový, luční med'],
    ['Med lesní', 'lesní med, medovicový'],
    ['Med akátový', 'akátový med'],
    ['Med lipový', 'lipový med'],
    ['Med řepkový', 'řepkový, slunečnicový med'],
    ['Med s příchutí', 'med s ořechy, skořicí, citronem'],
    ['Včelí produkty', 'medovina, propolis, pyl', 'med pro konzumaci'],
  ]),
  ex('dzem', 'Džem', P, 'Džemy, med a pomazánky', 'kg', 'druh ovoce a výrobku', [
    ['Jahodový džem', 'jahodový džem, marmeláda'],
    ['Meruňkový džem', 'meruňková marmeláda'],
    ['Malinový džem', 'malinový džem'],
    ['Švestkové povidla', 'povidla, povidlový džem'],
    ['Marmeláda citrusová', 'pomerančová, citronová, grapefruitová marmeláda'],
    ['Džem z lesního ovoce', 'borůvkový, brusinkový, rybízový džem'],
    ['Džem se sníženým obsahem cukru', 'džem light, bez cukru'],
  ]),
  nw('pomazanky-sladke', 'Sladké pomazánky', P, 'Džemy, med a pomazánky', 'kg', 'základ pomazánky', [
    ['Oříšková pomazánka', 'lískooříšková, nugátová pomazánka'],
    ['Arašídové máslo', 'arašídové máslo, jiná ořechová másla'],
    ['Čokoládová pomazánka', 'kakaová pomazánka'],
    ['Mandlové a jiné ořechové máslo', 'mandlové, kešu máslo'],
    ['Tahini', 'tahini, sezamová pasta'],
  ]),
  ex('pomazanky', 'Pomazánky', P, 'Džemy, med a pomazánky', 'kg', 'hlavní složka pomazánky', [
    ['Masová pomazánka', 'masová, jaterní pomazánka'],
    ['Sýrová pomazánka', 'tavená sýrová pomazánka, česneková, vlašská'],
    ['Zeleninová pomazánka', 'hummus, lečo, zeleninová, rostlinná pomazánka'],
    ['Tvarohová pomazánka', 'tvarohová pomazánka s bylinkami'],
    ['Rybí pomazánka', 'tuňáková, lososová, sardinková pomazánka'],
  ]),
  ex('cokolada-tabulkova', 'Čokoláda tabulková', P, 'Sladkosti', 'kg', 'druh čokoládové hmoty', [
    ['Mléčná čokoláda', 'mléčná tabulková čokoláda'],
    ['Hořká čokoláda', 'hořká čokoláda, vysoký obsah kakaa', 'čokoláda na vaření a kuvertura'],
    ['Bílá čokoláda', 'bílá čokoláda'],
    ['Čokoláda s přísadami nebo náplní', 'tabulka s ořechy, rozinkami, karamelem nebo krémovou náplní', 'čokoládová tyčinka v samostatném obalu'],
  ]),
  nw('bonbony-zvykaci', 'Bonbóny, žvýkačky a cukrovinky', P, 'Sladkosti', 'kg', 'druh cukrovinky', [
    ['Gumové bonbóny', 'gumoví medvídci, ovocné gumy'],
    ['Tvrdé bonbóny', 'drops, tvrdé bonbóny, mentolové'],
    ['Žvýkačky', 'žvýkačky bez cukru i s cukrem'],
    ['Lízátka', 'lízátka'],
    ['Karamely', 'měkké a tvrdé karamely, plněné karamely'],
    ['Bonboniéry', 'bonboniéry, čokoládové pralinky'],
    ['Pastilky a dražé', 'dražé, drážované, pastilky'],
    ['Marshmallow a želé', 'marshmallow, žvýkací želé, turecký med'],
  ]),
  nw('susenky-oplatky', 'Sušenky a oplatky', P, 'Sladkosti', 'kg', 'druh sušenky', [
    ['Máslové sušenky', 'máslové a jednoduché sušenky'],
    ['Čokoládové sušenky', 'sušenky s čokoládou nebo polevou'],
    ['Plněné sušenky', 'sušenky plněné krémem'],
    ['Perník', 'perníčky a perník plněný'],
    ['Piškotové sušenky', 'piškoty, lady fingers'],
    ['Celozrnné sušenky', 'sušenky celozrnné, ovesné, müsli'],
    ['Trvanlivé řezy', 'oplatky plněné, trvanlivé řezy a dortíky v balení'],
    ['Dortíky a koláčky balené', 'dortíky, mini koláčky, trvanlivé pečivo balené'],
  ]),
  nw('tycinky-sladke', 'Tyčinky a zdravé sladkosti', P, 'Sladkosti', 'kg', 'druh tyčinky', [
    ['Čokoládová tyčinka', 'mléčná čokoládová tyčinka s plnou náplní'],
    ['Müsli tyčinka', 'tyčinka z ovesných vloček'],
    ['Proteinová tyčinka', 'tyčinka s přidanými bílkovinami'],
    ['Ovocná tyčinka', 'tyčinka z ovoce a ořechů'],
    ['Rýžový a kukuřičný chlebíček', 'plochý křupavý chlebíček z pufované rýže nebo kukuřice'],
  ]),
  nw('zmrzliny', 'Zmrzliny a mražené dezerty', P, 'Mražené potraviny', 'l', 'forma zmrzliny', [
    ['Zmrzlina v kelímku', 'zmrzlina v kelímku nebo vaničce'],
    ['Nanuk', 'nanuky, zmrzlina na špejli'],
    ['Zmrzlinový kornout', 'zmrzlina v kornoutu nebo oplatce'],
    ['Ledová tříšť', 'ovocný led, sorbet, lední tříšť'],
    ['Mražený jogurt', 'zmrzlý jogurt, kefírová zmrzlina'],
    ['Zmrzlinový dort', 'zmrzlinový dort a dezert z několika vrstev'],
  ]),

  // --- Slané pochutiny -------------------------------------------------------------------------------------------------
  ex('chipsy-snacky', 'Chipsy', P, 'Slané pochutiny', 'kg', 'surovina chipsů', [
    ['Bramborové chipsy', 'chipsy z brambor, smažené i pečené'],
    ['Kukuřičné chipsy', 'chipsy z kukuřice označené jako chipsy', 'tortilla chipsy a nachos (jiný výrobek)'],
    ['Zeleninové chipsy', 'chipsy z batátů, červené řepy, zeleniny'],
  ]),
  nw('slane-snacky', 'Slané snacky', P, 'Slané pochutiny', 'kg', 'druh snacku', [
    ['Extrudované snacky', 'křupky, křupavé kuličky, pufované snacky'],
    ['Tortilla chipsy a nachos', 'tortilla chipsy, nachos'],
    ['Slané tyčinky a preclíky', 'slané tyčinky, preclíky'],
    ['Slané krekry', 'slané krekry a sušenky'],
    ['Popcorn', 'popcorn mikrovlnný i hotový'],
    ['Snackové směsi', 'směs oříšků, preclíků a křupek, snack mix'],
  ]),
  ex('orechy', 'Ořechy', P, 'Ořechy, semínka a sušené ovoce', 'kg', 'druh ořechu', [
    ['Mandle', 'mandle loupané i neloupané'],
    ['Vlašské ořechy', 'vlašské ořechy loupané'],
    ['Lískové ořechy', 'lískové ořechy'],
    ['Kešu ořechy', 'kešu'],
    ['Arašídy', 'arašídy loupané, solené, pražené'],
    ['Pistácie', 'pistácie solené'],
    ['Para ořechy a pekan', 'para, pekanové ořechy, makadamie'],
    ['Směs ořechů', 'směs jader, směs ořechů a ovoce'],
  ]),
  ex('seminka', 'Semínka', P, 'Ořechy, semínka a sušené ovoce', 'kg', 'druh semínka', [
    ['Slunečnicová semínka', 'slunečnicová semínka loupaná'],
    ['Dýňová semínka', 'dýňová semínka'],
    ['Lněné semínko', 'lněné semínko, drcené, zlatý len'],
    ['Chia semínka', 'chia'],
    ['Sezam', 'sezam, bílý i černý'],
    ['Mák', 'mák modrý, mletý'],
    ['Konopná semínka', 'konopná semínka a bílkovinné proteiny'],
  ]),
  nw('susene-ovoce', 'Sušené ovoce', P, 'Ořechy, semínka a sušené ovoce', 'kg', 'druh sušeného ovoce', [
    ['Rozinky', 'rozinky světlé i tmavé'],
    ['Sušené švestky', 'sušené švestky, slivky'],
    ['Sušené meruňky', 'sušené meruňky'],
    ['Datle', 'sušené datle'],
    ['Sušené fíky', 'sušené fíky'],
    ['Brusinky sušené', 'sušené brusinky, goji, kustovnice'],
    ['Kokos sušený', 'kokos strouhaný, kokosové plátky'],
    ['Sušená jablka a banány', 'chipsy z ovoce, sušená jablka, banánové plátky'],
  ]),

  // --- Nápoje -----------------------------------------------------------------------------------------------------------
  nw('voda-ochucena', 'Ochucená voda', P, 'Nápoje', 'l', 'sycení a příchuť', [
    ['Ochucená voda neperlivá', 'neperlivá voda s příchutí'],
    ['Ochucená voda perlivá', 'perlivá voda s příchutí'],
  ]),
  nw('limonady', 'Limonády a nealkoholické nápoje', P, 'Nápoje', 'l', 'druh sladkého nápoje', [
    ['Kolový nápoj', 'cola, zero cola'],
    ['Ovocná limonáda', 'pomerančová, citronová limonáda'],
    ['Tonic a ginger ale', 'tonic, bitter lemon, ginger ale'],
    ['Ledový čaj', 'ledový čaj'],
    ['Energetický nápoj', 'energetický nápoj, plechovka'],
    ['Iontový nápoj', 'sportovní, izotonický nápoj'],
    ['Sirup', 'koncentrovaný ovocný sirup'],
    ['Nápoj bez cukru', 'light, zero, sladidla'],
  ]),
  nw('dzusy', 'Džusy a ovocné šťávy', P, 'Nápoje', 'l', 'podíl ovoce a druh', [
    ['Džus 100 %', 'přímo lisovaná šťáva, 100 % ovoce'],
    ['Nektar', 'ovocný nektar s nižším obsahem ovoce'],
    ['Zeleninová šťáva', 'rajčatový, mrkvový džus'],
    ['Ovocný nápoj', 'ovocný nápoj se sníženým podílem ovoce'],
    ['Smoothie', 'smoothie, ovocné pyré k pití'],
  ]),
  nw('nahrazky-mleka-rostlinne', 'Rostlinné nápoje', P, 'Rostlinné alternativy', 'l', 'základní surovina', [
    ['Ovesný nápoj', 'ovesné mléko'],
    ['Sójový nápoj', 'sójové mléko'],
    ['Mandlový nápoj', 'mandlové mléko'],
    ['Kokosový nápoj', 'kokosové mléko do pití'],
    ['Rýžový nápoj', 'rýžové mléko'],
    ['Hrachový nápoj', 'hrachové mléko'],
    ['Nápoj z lískových ořechů', 'lískooříškové mléko'],
  ]),
  nw('rostlinne-alternativy-potravin', 'Rostlinné alternativy masa a mléčných výrobků', P, 'Rostlinné alternativy', 'kg', 'nahrazovaný výrobek', [
    ['Rostlinný jogurt', 'jogurty ze sóji, kokosu, ovsa'],
    ['Rostlinný sýr', 'sýr na rostlinné bázi'],
    ['Tofu', 'tofu přírodní, uzené'],
    ['Tempeh', 'tempeh'],
    ['Rostlinné maso', 'rostlinná mleté maso, burger, nugety, párky'],
    ['Seitan', 'seitan'],
    ['Rostlinná smetana', 'smetana ze sóji, ovsa, mandlí'],
  ]),
  ex('kava', 'Káva', P, 'Káva a čaj', 'kg', 'forma kávy (kromě mleté a zrnkové ze startovního registru)', [
    ['Káva instantní', 'rozpustná káva, granulát, 3v1'],
    ['Kávové kapsle', 'kapsle pro kávovary'],
    ['Kávové pody', 'pody ESE, papírové tablety'],
    ['Káva cappuccino a latte v prášku', 'instantní cappuccino, kávové směsi'],
    ['Kávoviny a náhražky', 'melta, cikorka, zrnková náhražka'],
    ['Studená káva', 'ledová káva v lahvi nebo plechovce'],
  ]),
  ex('caj', 'Čaj', P, 'Káva a čaj', 'kg', 'druh čajového listu nebo bylinné směsi', [
    ['Černý čaj', 'černý čaj sypaný i porcovaný, earl grey, ceylon'],
    ['Zelený čaj', 'zelený čaj, sencha, jasmínový zelený čaj'],
    ['Bílý čaj', 'bílý čaj'],
    ['Rooibos', 'rooibos, červený čaj z Jižní Afriky'],
    ['Ovocný čaj', 'ovocný čaj, ovocné směsi, šípkový čaj'],
    ['Bylinný čaj', 'bylinný čaj, heřmánek, máta, mateřídouška'],
  ]),
  // Pivo, voda neperlivá and the six reviewed families already have their own reviewed proposals
  // (docs/examples/product-subtype-registry-expansion-candidates.json) and are deliberately not repeated.
  ex('vino', 'Víno', P, 'Alkoholické nápoje', 'l', 'barva a šumivost vína', [
    ['Víno bílé', 'bílé víno suché, polosuché, polosladké'],
    ['Víno červené', 'červené víno'],
    ['Víno růžové', 'rosé'],
    ['Šumivé víno', 'sekt, prosecco, cava, champagne', 'nealkoholický sekt'],
  ]),
  ex('lihoviny', 'Lihoviny', P, 'Alkoholické nápoje', 'l', 'druh destilátu', [
    ['Whisky', 'whisky, bourbon, scotch'],
    ['Vodka', 'vodka'],
    ['Rum', 'rum světlý, tmavý, tuzemák'],
    ['Gin', 'gin'],
    ['Tequila', 'tequila, mezcal'],
    ['Brandy a koňak', 'brandy, koňak, vinné destiláty'],
    ['Ovocná pálenka', 'slivovice, hruškovice, meruňkovice'],
    ['Bylinná hořká lihovina', 'becherovka, fernet, hořké bylinné lihoviny'],
  ]),

  // --- Hotová jídla, mražené -------------------------------------------------------------------------------------------
  ex('mrazena-zelenina', 'Zelenina mražená', P, 'Mražené potraviny', 'kg', 'druh mražené zeleniny', [
    ['Mražený hrášek', 'mražený hrášek'],
    ['Mražený špenát', 'mražený špenát'],
    ['Mražená zeleninová směs', 'mražená směs zeleniny, vlašská, mexická'],
    ['Mražená brokolice a květák', 'brokolice, květák, růžičková kapusta'],
    ['Mražená kukuřice', 'mražená kukuřice'],
    ['Mražená houba', 'mražené žampiony, houby'],
  ]),
  ex('pizza-mrazena', 'Pizza mražená', P, 'Mražené potraviny', 'ks', 'druh mražené pizzy', [
    ['Pizza s šunkou', 'šunková pizza'],
    ['Pizza s uzeninou', 'salámová, pepperoni, slaninová'],
    ['Pizza sýrová', 'quattro formaggi, margherita'],
    ['Pizza bezmasá', 'zeleninová, vege pizza'],
    ['Pizza tenká', 'pizza tenké těsto, italská'],
    ['Pizza panini a mini', 'mini pizza, pizza rolls'],
  ]),
  nw('mrazena-hotova-jidla', 'Mražená hotová jídla', P, 'Mražené potraviny', 'kg', 'druh jídla', [
    ['Mražené těstoviny a rizoto', 'hotová jídla z těstovin, rizota, wok'],
    ['Mražené maso s přílohou', 'mražená jídla s masem a přílohou'],
    ['Mražené knedlíky a noky', 'knedlíky, noky, halušky'],
    ['Mražené smažené pokrmy', 'nugety, smažený sýr, řízek mražený'],
    ['Mražené pirohy a taštičky', 'pirohy, taštičky, ravioli'],
    ['Mražené bagety a croissanty', 'mražené pečivo k dopečení'],
    ['Mražené hranolky a bramborové výrobky', 'hranolky, krokety, bramborové placičky'],
    ['Mražené ryby obalované', 'rybí prsty, filé obalované'],
  ]),
  nw('hotova-jidla-chlazena', 'Hotová jídla chlazená', P, 'Lahůdky a hotová jídla', 'kg', 'druh jídla', [
    ['Salát hotový', 'salát bramborový, těstovinový, coleslaw'],
    ['Sendvič', 'sendvič chlazený, wrap'],
    ['Sushi', 'sushi sety, maki, nigiri'],
    ['Polévka chlazená', 'hotová polévka v kelímku'],
    ['Hotové jídlo s masem', 'řízek, guláš, svíčková hotová'],
    ['Sladké hotové jídlo', 'palačinky, knedlíky ovocné, lívance'],
  ]),
  nw('instantni-jidla', 'Instantní a zálivkové pokrmy', P, 'Trvanlivé potraviny', 'kg', 'druh pokrmu', [
    ['Instantní polévka', 'polévka v pytlíku, kelímku'],
    ['Instantní nudle', 'asijské instantní nudle'],
    ['Kaše instantní', 'instantní ovesná kaše, krupičná'],
    ['Bramborová kaše v prášku', 'bramborová kaše, bramborové knedlíky v prášku'],
    ['Rizoto a těstoviny v sáčku', 'směs na rizoto, těstoviny s omáčkou'],
    ['Hotová jídla v pouzdře', 'jídla ke zpracování v mikrovlnné troubě'],
  ]),
]
