import type { ProductPrice } from '@/lib/prices'
import type { Expense, Household, Item, Notification, PurchaseRecord, Store } from '@/lib/types'

const PRICE_DATE = '2026-09-19'

export const initialItems: Item[] = [
  { id: '1', name: 'Mléko polotučné', detail: '2 l · Mlékárna Kunín', price: 44.9, quantity: 2, unit: 'l', category: 'Potraviny', done: false, color: 'bg-sky-100 text-sky-700', priority: 'Normální', store: 'Lidl', onSale: true },
  { id: '2', name: 'Banány', detail: '1 kg · volné', price: 34.9, quantity: 1, unit: 'kg', category: 'Potraviny', done: false, color: 'bg-amber-100 text-amber-700', priority: 'Normální' },
  { id: '3', name: 'Kuřecí prsa', detail: '500 g · chlazené', price: 89.9, quantity: 1, unit: 'g', category: 'Potraviny', done: true, color: 'bg-rose-100 text-rose-700', priority: 'Vysoká', store: 'Albert', onSale: true },
  { id: '4', name: 'Toaletní papír', detail: '8 ks · Softy', price: 79.9, quantity: 1, unit: 'ks', category: 'Drogerie', done: false, color: 'bg-violet-100 text-violet-700', priority: 'Nízká' },
]

export const initialNotifications: Notification[] = [
  { id: '1', title: 'Nová akce v Lidlu', detail: 'Mléko je dnes o 20 % levnější.', unread: true },
  { id: '2', title: 'Rozpočet je pod kontrolou', detail: 'Zbývá vám 4 650 Kč do konce měsíce.', unread: true },
  { id: '3', title: 'Petr doplnil seznam', detail: 'Přidal položku „Ovesné vločky".', unread: false },
]

export const initialExpenses: Expense[] = [
  { id: '1', amount: 2350, note: 'Týdenní nákup potravin', category: 'Potraviny', subcategory: null, purchaseId: null, date: '2026-09-03' },
  { id: '2', amount: 890, note: 'Drogerie a hygiena', category: 'Drogerie', subcategory: null, purchaseId: null, date: '2026-09-06' },
  { id: '3', amount: 1200, note: 'Oblečení pro děti', category: 'Děti', subcategory: null, purchaseId: null, date: '2026-09-09' },
  { id: '4', amount: 1980, note: 'Nákup v Kauflandu', category: 'Potraviny', subcategory: null, purchaseId: null, date: '2026-09-13' },
  { id: '5', amount: 430, note: 'Čisticí prostředky', category: 'Domácnost', subcategory: null, purchaseId: null, date: '2026-09-16' },
  { id: '6', amount: 500, note: 'Různé drobnosti', category: 'Ostatní', subcategory: null, purchaseId: null, date: '2026-09-18' },
]

export const initialShoppingLists = ['Týdenní nákup', 'Lidl', 'Drogerie', 'Děti']

export const initialHousehold: Household = {
  id: 'seed-household',
  name: 'Rodina Králových',
  monthlyBudget: 12000,
  members: [
    {
      id: '1',
      name: 'Lucie Králová',
      role: 'Správce domácnosti',
      age: 34,
      preferences: 'Bez omezení',
      favoriteFoods: ['Kuřecí maso', 'Zelenina'],
      dislikedFoods: ['Ryby'],
      allergies: [],
    },
    {
      id: '2',
      name: 'Petr Král',
      role: 'Člen domácnosti',
      age: 36,
      preferences: 'Bez omezení',
      favoriteFoods: ['Těstoviny'],
      dislikedFoods: [],
      allergies: ['Ořechy'],
    },
  ],
  children: [
    { id: '1', name: 'Anna', age: 7, preferences: 'Sladké snídaně', specialNeeds: '' },
    { id: '2', name: 'Tomáš', age: 4, preferences: 'Bez kousků zeleniny', specialNeeds: 'Alergie na lepek' },
  ],
  preferences: {
    preferredBrands: ['Milka', 'Kunín'],
    preferredStores: ['Lidl', 'Albert'],
    preferredProducts: ['Ovesné vločky', 'Řecký jogurt'],
    excludedProducts: ['Energetické nápoje'],
    priceSensitivity: 'Vyvážené',
    qualityPreference: 'Standardní',
    preferCzechProducts: true,
  },
  restrictions: ['Bez laktózy pro Tomáše'],
}

/** Seed fixtures: a store plus the products the seed gives it prices for (lib/db/seed.ts). */
export type SeedStore = Store & { availableProducts: string[] }

export const stores: SeedStore[] = [
  {
    id: 'lidl-budejovicka',
    chain: 'Lidl',
    name: 'Lidl Budějovická',
    address: 'Budějovická 1, 140 00 Praha 4',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.0522, lng: 14.4491 },
    hours: 'Otevřeno do 21:00',
    dealsCount: 2,
    availableProducts: ['Mléko polotučné', 'Toaletní papír', 'Banány'],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-krc',
    chain: 'Albert',
    name: 'Albert Krč',
    address: 'Sezimova 15, 140 00 Praha 4',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.0361, lng: 14.4381 },
    hours: 'Otevřeno do 22:00',
    dealsCount: 1,
    availableProducts: ['Kuřecí prsa', 'Banány', 'Vejce'],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'kaufland-chodov',
    chain: 'Kaufland',
    name: 'Kaufland Chodov',
    address: 'Roztylská 19, 140 00 Praha 4',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.0219, lng: 14.4909 },
    hours: 'Otevřeno do 21:00',
    dealsCount: 8,
    availableProducts: ['Toaletní papír', 'Rýže', 'Kuřecí prsa'],
    color: 'bg-[#b9d8f5]',
  },
  {
    id: 'billa-nusle',
    chain: 'Billa',
    name: 'Billa Nusle',
    address: 'Táborská 42, 140 00 Praha 4',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.0645, lng: 14.4472 },
    hours: 'Otevřeno do 21:00',
    dealsCount: 4,
    availableProducts: ['Máslo', 'Vejce', 'Mléko polotučné'],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'penny-michle',
    chain: 'Penny',
    name: 'Penny Michle',
    address: 'Michelská 76, 140 00 Praha 4',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.0525, lng: 14.4633 },
    hours: 'Otevřeno do 20:00',
    dealsCount: 3,
    availableProducts: ['Těstoviny', 'Rajčata', 'Toaletní papír'],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'jip-branik',
    chain: 'JIP',
    name: 'JIP Braník',
    address: 'Branická 48, 140 00 Praha 4',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.0234, lng: 14.4136 },
    hours: 'Otevřeno do 19:00',
    dealsCount: 4,
    availableProducts: ['Mléko polotučné', 'Pečivo'],
    color: 'bg-[#c9b8ef]',
  },

  // Real branches nationwide, from OpenStreetMap (openstreetmap.org contributors, ODbL license),
  // fetched 2026-09-21 via the public Overpass API. Curated for geographic spread across CZ
  // regions rather than every branch (there are 850+ nationwide across these 6 chains). No price
  // data exists for these yet (dealsCount/availableProducts stay honest at 0/[]), unlike the six
  // Prague locations above which already have seeded prices/deals.
  {
    id: 'lidl-praha',
    chain: 'Lidl',
    name: 'Lidl Praha',
    address: 'Seifertova 2919/12a, Praha',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.084621, lng: 14.446424 },
    hours: 'Mo-Sa 07:00-21:00; Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-praha-4',
    chain: 'Albert',
    name: 'Albert Praha 4',
    address: 'Zdislavická 583, Praha 4',
    city: 'Praha 4',
    country: 'Česká republika',
    gps: { lat: 50.017302, lng: 14.443231 },
    hours: 'Otevírací doba neuvedena',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'billa-praha',
    chain: 'Billa',
    name: 'Billa Praha',
    address: 'Vodičkova 710/31, Praha',
    city: 'Praha',
    country: 'Česká republika',
    gps: { lat: 50.081111, lng: 14.424262 },
    hours: 'Mo-Sa 07:00-22:00; Su 08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'penny-praha-4',
    chain: 'Penny',
    name: 'Penny Praha 4 (PENNY)',
    address: 'Choceradská 3214, Praha 4',
    city: 'Praha 4',
    country: 'Česká republika',
    gps: { lat: 50.048105, lng: 14.49322 },
    hours: 'Mo-Su 07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'lidl-brno',
    chain: 'Lidl',
    name: 'Lidl Brno',
    address: 'Šumavská 519/35, Brno',
    city: 'Brno',
    country: 'Česká republika',
    gps: { lat: 49.209597, lng: 16.591558 },
    hours: 'Mo-Sa 07:00-22:00; Su 08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-brno-lisen',
    chain: 'Albert',
    name: 'Albert Brno - Líšeň',
    address: 'Masarova 2428/9, Brno - Líšeň',
    city: 'Brno - Líšeň',
    country: 'Česká republika',
    gps: { lat: 49.206152, lng: 16.676158 },
    hours: 'Mo-Su 07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'billa-brno',
    chain: 'Billa',
    name: 'Billa Brno',
    address: 'Sedláčkova 2557/4, Brno',
    city: 'Brno',
    country: 'Česká republika',
    gps: { lat: 49.201964, lng: 16.667798 },
    hours: 'Mo-Sa 07:00-22:00; Su 08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'penny-brno',
    chain: 'Penny',
    name: 'Penny Brno',
    address: 'Okružní 732/5, Brno',
    city: 'Brno',
    country: 'Česká republika',
    gps: { lat: 49.22177, lng: 16.625724 },
    hours: 'Mo-Su 07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'lidl-ostrava',
    chain: 'Lidl',
    name: 'Lidl Ostrava',
    address: 'Dr. Martínka 14a, Ostrava',
    city: 'Ostrava',
    country: 'Česká republika',
    gps: { lat: 49.785271, lng: 18.265658 },
    hours: 'Mo-Sa 07:00-21:00; Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-ostrava',
    chain: 'Albert',
    name: 'Albert Ostrava',
    address: 'Předškolní 680/4, Ostrava',
    city: 'Ostrava',
    country: 'Česká republika',
    gps: { lat: 49.781439, lng: 18.22219 },
    hours: '07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'lidl-plzen',
    chain: 'Lidl',
    name: 'Lidl Plzeň',
    address: 'Studentská 1709/131, Plzeň',
    city: 'Plzeň',
    country: 'Česká republika',
    gps: { lat: 49.773045, lng: 13.347172 },
    hours: 'Mo-Sa 07:00-21:00; Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-plzen',
    chain: 'Albert',
    name: 'Albert Plzeň',
    address: 'Karla Steinera 910/7, Plzeň',
    city: 'Plzeň',
    country: 'Česká republika',
    gps: { lat: 49.743323, lng: 13.329246 },
    hours: 'Mo-Su 07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'kaufland-plzen',
    chain: 'Kaufland',
    name: 'Kaufland Plzeň',
    address: 'Sukova 2895/23, Plzeň',
    city: 'Plzeň',
    country: 'Česká republika',
    gps: { lat: 49.728077, lng: 13.361801 },
    hours: 'Mo-Su 07:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#b9d8f5]',
  },
  {
    id: 'billa-plzen',
    chain: 'Billa',
    name: 'Billa Plzeň',
    address: 'Studentská 55, Plzeň',
    city: 'Plzeň',
    country: 'Česká republika',
    gps: { lat: 49.775029, lng: 13.36205 },
    hours: 'Mo-Sa 07:00-21:00, Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'penny-plzen',
    chain: 'Penny',
    name: 'Penny Plzeň',
    address: 'Částkova 1185/80, Plzeň',
    city: 'Plzeň',
    country: 'Česká republika',
    gps: { lat: 49.734697, lng: 13.405333 },
    hours: 'Mo-Su 07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'albert-olomouc',
    chain: 'Albert',
    name: 'Albert Olomouc',
    address: 'Janského 459/22, Olomouc',
    city: 'Olomouc',
    country: 'Česká republika',
    gps: { lat: 49.578307, lng: 17.242622 },
    hours: 'Mo-Su 07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'penny-olomouc',
    chain: 'Penny',
    name: 'Penny Olomouc',
    address: 'Wolkerova 1213/31, Olomouc',
    city: 'Olomouc',
    country: 'Česká republika',
    gps: { lat: 49.586375, lng: 17.243136 },
    hours: 'Mo-Fr 07:00-21:00; Sa,Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'albert-liberec',
    chain: 'Albert',
    name: 'Albert Liberec',
    address: 'České mládeže 456/26, Liberec',
    city: 'Liberec',
    country: 'Česká republika',
    gps: { lat: 50.741798, lng: 15.050713 },
    hours: '08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'lidl-hradec-kralove',
    chain: 'Lidl',
    name: 'Lidl Hradec Králové',
    address: 'Pilnáčkova 410/7, Hradec Králové',
    city: 'Hradec Králové',
    country: 'Česká republika',
    gps: { lat: 50.217945, lng: 15.836377 },
    hours: 'Mo-Fr 07:00-22:00; Sa,Su 08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-hradec-kralove',
    chain: 'Albert',
    name: 'Albert Hradec Králové',
    address: 'Víta Nejedlého 1063, Hradec Králové',
    city: 'Hradec Králové',
    country: 'Česká republika',
    gps: { lat: 50.212007, lng: 15.8526 },
    hours: 'Mo-Su 07:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'lidl-ceske-budejovice',
    chain: 'Lidl',
    name: 'Lidl České Budějovice',
    address: 'B. Němcové 2148, České Budějovice',
    city: 'České Budějovice',
    country: 'Česká republika',
    gps: { lat: 48.967715, lng: 14.471481 },
    hours: 'Mo-Sa 07:00-22:00; Su 08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-ceske-budejovice',
    chain: 'Albert',
    name: 'Albert České Budějovice',
    address: 'Suchovrbenské nám. 708/2, České Budějovice',
    city: 'České Budějovice',
    country: 'Česká republika',
    gps: { lat: 48.97093, lng: 14.503706 },
    hours: 'Mo-Su 07:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'billa-ceske-budejovice',
    chain: 'Billa',
    name: 'Billa České Budějovice',
    address: 'J. Opletala 926/20, České Budějovice',
    city: 'České Budějovice',
    country: 'Česká republika',
    gps: { lat: 48.981889, lng: 14.446341 },
    hours: 'Mo-Sa 07:00-20:00; Su 08:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'lidl-usti-nad-labem',
    chain: 'Lidl',
    name: 'Lidl Ústí nad Labem',
    address: 'Krčínova 891/5, Ústí nad Labem',
    city: 'Ústí nad Labem',
    country: 'Česká republika',
    gps: { lat: 50.666648, lng: 14.073528 },
    hours: 'Mo-Sa 07:00-20:00; Su 08:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-usti-nad-labem',
    chain: 'Albert',
    name: 'Albert Ústí nad Labem',
    address: 'Krušnohorská 3371/2, Ústí nad Labem',
    city: 'Ústí nad Labem',
    country: 'Česká republika',
    gps: { lat: 50.677823, lng: 14.036713 },
    hours: 'Otevírací doba neuvedena',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'penny-usti-nad-labem',
    chain: 'Penny',
    name: 'Penny Ústí nad Labem (PENNY)',
    address: 'Skorotická 782, Ústí nad Labem',
    city: 'Ústí nad Labem',
    country: 'Česká republika',
    gps: { lat: 50.68083, lng: 14.00818 },
    hours: 'Mo-Sa 07:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'lidl-pardubice',
    chain: 'Lidl',
    name: 'Lidl Pardubice',
    address: 'Palackého třída 2760, Pardubice',
    city: 'Pardubice',
    country: 'Česká republika',
    gps: { lat: 50.032724, lng: 15.750031 },
    hours: 'Mo-Sa 07:00-22:00; Su 08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-pardubice',
    chain: 'Albert',
    name: 'Albert Pardubice (Albert Pardubice, OC)',
    address: 'Palackého třída 2748, Pardubice',
    city: 'Pardubice',
    country: 'Česká republika',
    gps: { lat: 50.034499, lng: 15.752753 },
    hours: '07:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'billa-pardubice',
    chain: 'Billa',
    name: 'Billa Pardubice',
    address: 'náměstí Republiky 1400, Pardubice',
    city: 'Pardubice',
    country: 'Česká republika',
    gps: { lat: 50.037995, lng: 15.776455 },
    hours: 'Mo-Fr 07:00-21:00; Sa 07:00-21:00; Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'albert-zlin',
    chain: 'Albert',
    name: 'Albert Zlín',
    address: 'Okružní 4701, Zlín',
    city: 'Zlín',
    country: 'Česká republika',
    gps: { lat: 49.233129, lng: 17.659448 },
    hours: 'Mo-Fr 08:00-18:00; Sa 08:00-12:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'albert-karlovy-vary',
    chain: 'Albert',
    name: 'Albert Karlovy Vary',
    address: 'Horova 1223/1, Karlovy Vary',
    city: 'Karlovy Vary',
    country: 'Česká republika',
    gps: { lat: 50.231633, lng: 12.870018 },
    hours: 'Mo-Su 06:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'billa-karlovy-vary',
    chain: 'Billa',
    name: 'Billa Karlovy Vary',
    address: 'T. G. Masaryka 623/12, Karlovy Vary',
    city: 'Karlovy Vary',
    country: 'Česká republika',
    gps: { lat: 50.229502, lng: 12.871595 },
    hours: 'Mo-Sa 07:00-21:00; Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'albert-jihlava',
    chain: 'Albert',
    name: 'Albert Jihlava',
    address: 'Hradební 5440/1, Jihlava',
    city: 'Jihlava',
    country: 'Česká republika',
    gps: { lat: 49.392336, lng: 15.592392 },
    hours: 'Mo-Su 08:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'lidl-kladno',
    chain: 'Lidl',
    name: 'Lidl Kladno',
    address: 'Arménská, Kladno',
    city: 'Kladno',
    country: 'Česká republika',
    gps: { lat: 50.134489, lng: 14.138541 },
    hours: 'Mo-Sa 07:00-21:00; Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#d7f36b]',
  },
  {
    id: 'albert-kladno',
    chain: 'Albert',
    name: 'Albert Kladno',
    address: 'Obránců míru 2427, Kladno',
    city: 'Kladno',
    country: 'Česká republika',
    gps: { lat: 50.13447, lng: 14.128929 },
    hours: 'Mo-Su 07:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'billa-kladno',
    chain: 'Billa',
    name: 'Billa Kladno',
    address: 'Arménská 3277, Kladno',
    city: 'Kladno',
    country: 'Česká republika',
    gps: { lat: 50.132717, lng: 14.140125 },
    hours: 'Mo-Fr 07:00-21:00; Sa,Su 08:00-21:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f3c0d3]',
  },
  {
    id: 'albert-most',
    chain: 'Albert',
    name: 'Albert Most',
    address: 'Topolová 1513, Most',
    city: 'Most',
    country: 'Česká republika',
    gps: { lat: 50.496067, lng: 13.648347 },
    hours: 'Otevírací doba neuvedena',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'penny-most',
    chain: 'Penny',
    name: 'Penny Most (PENNY)',
    address: 'Moskevská 1999, Most',
    city: 'Most',
    country: 'Česká republika',
    gps: { lat: 50.505481, lng: 13.643688 },
    hours: '07:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'albert-kutna-hora',
    chain: 'Albert',
    name: 'Albert Kutná Hora',
    address: 'Masarykova 187, Kutná Hora',
    city: 'Kutná Hora',
    country: 'Česká republika',
    gps: { lat: 49.96005, lng: 15.28406 },
    hours: 'Mo-Su 07:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'kaufland-kutna-hora',
    chain: 'Kaufland',
    name: 'Kaufland Kutná Hora',
    address: 'Ortenova, Kutná Hora',
    city: 'Kutná Hora',
    country: 'Česká republika',
    gps: { lat: 49.960859, lng: 15.283743 },
    hours: 'PH,Mo-Su 07:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#b9d8f5]',
  },
  {
    id: 'albert-trebic',
    chain: 'Albert',
    name: 'Albert Třebíč',
    address: 'Modřínová 694/5, Třebíč',
    city: 'Třebíč',
    country: 'Česká republika',
    gps: { lat: 49.218671, lng: 15.892654 },
    hours: 'Otevírací doba neuvedena',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'kaufland-trebic',
    chain: 'Kaufland',
    name: 'Kaufland Třebíč',
    address: 'Spojovací 1345, Třebíč',
    city: 'Třebíč',
    country: 'Česká republika',
    gps: { lat: 49.201868, lng: 15.890197 },
    hours: 'Otevírací doba neuvedena',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#b9d8f5]',
  },
  {
    id: 'albert-jablonec-nad-nisou',
    chain: 'Albert',
    name: 'Albert Jablonec nad Nisou',
    address: 'Želivského 5050/2, Jablonec nad Nisou',
    city: 'Jablonec nad Nisou',
    country: 'Česká republika',
    gps: { lat: 50.735573, lng: 15.160857 },
    hours: '07:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'kaufland-jablonec-nad-nisou',
    chain: 'Kaufland',
    name: 'Kaufland Jablonec nad Nisou',
    address: 'U Kostela 4754/37, Jablonec nad Nisou',
    city: 'Jablonec nad Nisou',
    country: 'Česká republika',
    gps: { lat: 50.73885, lng: 15.168648 },
    hours: '07:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#b9d8f5]',
  },
  {
    id: 'penny-jablonec-nad-nisou',
    chain: 'Penny',
    name: 'Penny Jablonec nad Nisou',
    address: 'Palackého 4570/96, Jablonec nad Nisou',
    city: 'Jablonec nad Nisou',
    country: 'Česká republika',
    gps: { lat: 50.744512, lng: 15.156781 },
    hours: '07:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'albert-prerov',
    chain: 'Albert',
    name: 'Albert Přerov',
    address: 'Bayerova 646/3, Přerov',
    city: 'Přerov',
    country: 'Česká republika',
    gps: { lat: 49.454392, lng: 17.455425 },
    hours: 'Otevírací doba neuvedena',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f4b183]',
  },
  {
    id: 'kaufland-prerov',
    chain: 'Kaufland',
    name: 'Kaufland Přerov',
    address: 'Želatovská 3564/42, Přerov',
    city: 'Přerov',
    country: 'Česká republika',
    gps: { lat: 49.448799, lng: 17.473134 },
    hours: 'Mo-Su 07:00-22:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#b9d8f5]',
  },
  {
    id: 'penny-prerov',
    chain: 'Penny',
    name: 'Penny Přerov (PENNY)',
    address: 'tř. Gen. Janouška 2854/2, Přerov',
    city: 'Přerov',
    country: 'Česká republika',
    gps: { lat: 49.450949, lng: 17.470105 },
    hours: 'Mo-Su 07:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#f6d38b]',
  },
  {
    id: 'jip-jilemnice',
    chain: 'JIP',
    name: 'JIP Jilemnice',
    address: 'V Jilmu 229, Jilemnice',
    city: 'Jilemnice',
    country: 'Česká republika',
    gps: { lat: 50.605942, lng: 15.509403 },
    hours: 'Mo-Su 07:00-20:00',
    dealsCount: 0,
    availableProducts: [],
    color: 'bg-[#c9b8ef]',
  },
]

export const initialPurchaseHistory: PurchaseRecord[] = [
  {
    id: '1',
    date: '2026-07-05',
    store: 'Lidl',
    items: [
      { name: 'Mléko polotučné', quantity: 2, unit: 'l', price: 37.9 },
      { name: 'Banány', quantity: 1, unit: 'kg', price: 29.9 },
      { name: 'Toaletní papír', quantity: 1, unit: 'ks', price: 74.9 },
    ],
    total: 180.6,
  },
  {
    id: '2',
    date: '2026-07-19',
    store: 'Albert',
    items: [
      { name: 'Kuřecí prsa', quantity: 1, unit: 'kg', price: 199.9 },
      { name: 'Vejce', quantity: 1, unit: 'ks', price: 59.9 },
    ],
    total: 259.8,
  },
  {
    id: '3',
    date: '2026-08-02',
    store: 'Lidl',
    items: [
      { name: 'Mléko polotučné', quantity: 2, unit: 'l', price: 39.9 },
      { name: 'Banány', quantity: 1, unit: 'kg', price: 33.9 },
      { name: 'Rýže', quantity: 1, unit: 'kg', price: 44.9 },
    ],
    total: 152.6,
  },
  {
    id: '4',
    date: '2026-08-16',
    store: 'Kaufland',
    items: [
      { name: 'Toaletní papír', quantity: 1, unit: 'ks', price: 79.9 },
      { name: 'Kuřecí prsa', quantity: 1, unit: 'kg', price: 169.9 },
      { name: 'Rýže', quantity: 2, unit: 'kg', price: 42.9 },
    ],
    total: 335.6,
    discount: 25,
  },
  {
    id: '5',
    date: '2026-09-03',
    store: 'Lidl',
    items: [
      { name: 'Mléko polotučné', quantity: 2, unit: 'l', price: 37.9 },
      { name: 'Banány', quantity: 1, unit: 'kg', price: 29.9 },
      { name: 'Vejce', quantity: 1, unit: 'ks', price: 58.9 },
    ],
    total: 164.6,
  },
  {
    id: '6',
    date: '2026-09-13',
    store: 'Kaufland',
    items: [
      { name: 'Toaletní papír', quantity: 1, unit: 'ks', price: 64.9 },
      { name: 'Rýže', quantity: 1, unit: 'kg', price: 42.9 },
      { name: 'Kuřecí prsa', quantity: 1, unit: 'kg', price: 169.9 },
    ],
    total: 277.7,
    discount: 15,
  },
]

export const PRODUCT_PRICES: ProductPrice[] = [
  {
    productName: 'Mléko polotučné',
    category: 'Potraviny',
    prices: [
      { store: 'Lidl', regularPrice: 39.9, dealPrice: 29.9, dealValidUntil: '2026-09-26', unit: 'l', unitPrice: 29.9, recordedAt: PRICE_DATE },
      { store: 'Albert', regularPrice: 42.9, unit: 'l', unitPrice: 42.9, recordedAt: PRICE_DATE },
      { store: 'Kaufland', regularPrice: 37.9, unit: 'l', unitPrice: 37.9, recordedAt: PRICE_DATE },
      { store: 'Billa', regularPrice: 44.9, unit: 'l', unitPrice: 44.9, recordedAt: PRICE_DATE },
      { store: 'Penny', regularPrice: 38.9, unit: 'l', unitPrice: 38.9, recordedAt: PRICE_DATE },
    ],
  },
  {
    productName: 'Kuřecí prsa',
    category: 'Potraviny',
    prices: [
      { store: 'Lidl', regularPrice: 149.9, unit: 'kg', unitPrice: 149.9, recordedAt: PRICE_DATE },
      { store: 'Albert', regularPrice: 199.9, dealPrice: 159.9, dealValidUntil: '2026-09-24', unit: 'kg', unitPrice: 159.9, recordedAt: PRICE_DATE },
      { store: 'Kaufland', regularPrice: 169.9, unit: 'kg', unitPrice: 169.9, recordedAt: PRICE_DATE },
      { store: 'Billa', regularPrice: 189.9, unit: 'kg', unitPrice: 189.9, recordedAt: PRICE_DATE },
    ],
  },
  {
    productName: 'Banány',
    category: 'Potraviny',
    prices: [
      { store: 'Lidl', regularPrice: 32.9, unit: 'kg', unitPrice: 32.9, recordedAt: PRICE_DATE },
      { store: 'Albert', regularPrice: 34.9, unit: 'kg', unitPrice: 34.9, recordedAt: PRICE_DATE },
      { store: 'Kaufland', regularPrice: 29.9, unit: 'kg', unitPrice: 29.9, recordedAt: PRICE_DATE },
      { store: 'Penny', regularPrice: 33.9, unit: 'kg', unitPrice: 33.9, recordedAt: PRICE_DATE },
    ],
  },
  {
    productName: 'Toaletní papír',
    category: 'Drogerie',
    prices: [
      { store: 'Kaufland', regularPrice: 79.9, dealPrice: 64.9, dealValidUntil: '2026-09-30', unit: 'ks', unitPrice: 8.1, recordedAt: PRICE_DATE },
      { store: 'Lidl', regularPrice: 74.9, unit: 'ks', unitPrice: 9.4, recordedAt: PRICE_DATE },
      { store: 'Billa', regularPrice: 84.9, unit: 'ks', unitPrice: 10.6, recordedAt: PRICE_DATE },
      { store: 'Penny', regularPrice: 76.9, unit: 'ks', unitPrice: 9.6, recordedAt: PRICE_DATE },
    ],
  },
]
