-- Product types (druhy zboží), phase 1 of docs/12_PRODUCT_TYPES.md (owner-approved 2026-10-03/04).
-- Additive: two tables for the types and their groups, a membership table, and a nullable type on
-- products. The rows mirror lib/product-types.ts (PRODUCT_TYPES, PRODUCT_TYPE_GROUPS); a database test
-- checks they agree. Products get their type from `pnpm db:assign-product-types`, not here.
CREATE TABLE IF NOT EXISTS "product_types" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "key" text NOT NULL UNIQUE,
  "name" text NOT NULL,
  "category" "item_category" NOT NULL,
  "unit" "item_unit" NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "product_type_groups" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "key" text NOT NULL UNIQUE,
  "name" text NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "product_type_group_members" (
  "group_id" uuid NOT NULL REFERENCES "product_type_groups"("id") ON DELETE CASCADE,
  "type_id" uuid NOT NULL REFERENCES "product_types"("id") ON DELETE CASCADE,
  PRIMARY KEY ("group_id", "type_id")
);--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "product_type_id" uuid REFERENCES "product_types"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "product_type_source" text;--> statement-breakpoint
ALTER TABLE "products" DROP CONSTRAINT IF EXISTS "products_product_type_source_valid";--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_product_type_source_valid" CHECK ("product_type_source" IS NULL OR "product_type_source" IN ('rule', 'manual', 'alias'));--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "products_product_type_idx" ON "products" ("product_type_id");--> statement-breakpoint
INSERT INTO "product_types" ("key", "name", "category", "unit") VALUES
  ('maslo', 'Máslo', 'Potraviny', 'kg'),
  ('mleko-polotucne', 'Mléko polotučné', 'Potraviny', 'l'),
  ('mleko-plnotucne', 'Mléko plnotučné', 'Potraviny', 'l'),
  ('mleko-bez-laktozy', 'Mléko bez laktózy', 'Potraviny', 'l'),
  ('smetana-na-vareni', 'Smetana na vaření', 'Potraviny', 'l'),
  ('smetana-ke-slehani', 'Smetana ke šlehání', 'Potraviny', 'l'),
  ('zakysana-smetana', 'Zakysaná smetana', 'Potraviny', 'kg'),
  ('jogurt-bily', 'Bílý jogurt', 'Potraviny', 'kg'),
  ('tvaroh', 'Tvaroh', 'Potraviny', 'kg'),
  ('eidam', 'Eidam', 'Potraviny', 'kg'),
  ('gouda', 'Gouda', 'Potraviny', 'kg'),
  ('mozzarella', 'Mozzarella', 'Potraviny', 'kg'),
  ('balkansky-syr', 'Balkánský sýr', 'Potraviny', 'kg'),
  ('hermelin', 'Hermelín a camembert', 'Potraviny', 'kg'),
  ('parmazan', 'Parmazán', 'Potraviny', 'kg'),
  ('taveny-syr', 'Tavený sýr', 'Potraviny', 'kg'),
  ('niva', 'Niva', 'Potraviny', 'kg'),
  ('cottage', 'Cottage', 'Potraviny', 'kg'),
  ('vejce', 'Vejce', 'Potraviny', 'ks'),
  ('rohlik', 'Rohlík', 'Potraviny', 'ks'),
  ('chleb', 'Chléb', 'Potraviny', 'kg'),
  ('toustovy-chleb', 'Toustový chléb', 'Potraviny', 'kg'),
  ('houska', 'Houska a kaiserka', 'Potraviny', 'ks'),
  ('bageta', 'Bageta', 'Potraviny', 'ks'),
  ('jablka', 'Jablka', 'Potraviny', 'kg'),
  ('banany', 'Banány', 'Potraviny', 'kg'),
  ('pomerance', 'Pomeranče', 'Potraviny', 'kg'),
  ('mandarinky', 'Mandarinky a klementinky', 'Potraviny', 'kg'),
  ('citrony', 'Citrony', 'Potraviny', 'kg'),
  ('hrusky', 'Hrušky', 'Potraviny', 'kg'),
  ('hrozny', 'Hrozny', 'Potraviny', 'kg'),
  ('jahody', 'Jahody', 'Potraviny', 'kg'),
  ('boruvky', 'Borůvky', 'Potraviny', 'kg'),
  ('maliny', 'Maliny', 'Potraviny', 'kg'),
  ('avokado', 'Avokádo', 'Potraviny', 'ks'),
  ('rajcata', 'Rajčata', 'Potraviny', 'kg'),
  ('okurky', 'Okurky salátové', 'Potraviny', 'ks'),
  ('paprika', 'Paprika', 'Potraviny', 'kg'),
  ('brambory', 'Brambory', 'Potraviny', 'kg'),
  ('cibule', 'Cibule', 'Potraviny', 'kg'),
  ('cesnek', 'Česnek', 'Potraviny', 'kg'),
  ('mrkev', 'Mrkev', 'Potraviny', 'kg'),
  ('salat', 'Salát hlávkový a ledový', 'Potraviny', 'ks'),
  ('zeli', 'Zelí', 'Potraviny', 'kg'),
  ('zampiony', 'Žampiony', 'Potraviny', 'kg'),
  ('brokolice', 'Brokolice', 'Potraviny', 'kg'),
  ('kureci-prsa', 'Kuřecí prsa a prsní řízky', 'Potraviny', 'kg'),
  ('kureci-stehna', 'Kuřecí stehna a čtvrtky', 'Potraviny', 'kg'),
  ('kureci-kridla', 'Kuřecí křídla', 'Potraviny', 'kg'),
  ('kure-cele', 'Kuře celé a půlky', 'Potraviny', 'kg'),
  ('kureci-mlete', 'Kuřecí mleté maso', 'Potraviny', 'kg'),
  ('kureci-vnitrnosti', 'Kuřecí vnitřnosti', 'Potraviny', 'kg'),
  ('kureci-na-polevku', 'Kuřecí díly na polévku', 'Potraviny', 'kg'),
  ('veprova-krkovice', 'Vepřová krkovice', 'Potraviny', 'kg'),
  ('veprova-pecene', 'Vepřová pečeně a kotlety', 'Potraviny', 'kg'),
  ('veprova-panenka', 'Vepřová panenka', 'Potraviny', 'kg'),
  ('veprova-kyta', 'Vepřová kýta', 'Potraviny', 'kg'),
  ('veprova-plec', 'Vepřová plec', 'Potraviny', 'kg'),
  ('veprovy-bucek', 'Vepřový bůček', 'Potraviny', 'kg'),
  ('veprova-zebra', 'Vepřová žebra', 'Potraviny', 'kg'),
  ('veprove-mlete', 'Vepřové mleté maso', 'Potraviny', 'kg'),
  ('veprove-na-gulas', 'Vepřové na guláš', 'Potraviny', 'kg'),
  ('hovezi-svickova', 'Hovězí svíčková', 'Potraviny', 'kg'),
  ('hovezi-zadni', 'Hovězí zadní', 'Potraviny', 'kg'),
  ('hovezi-predni', 'Hovězí přední', 'Potraviny', 'kg'),
  ('hovezi-steak', 'Hovězí steak', 'Potraviny', 'kg'),
  ('hovezi-mlete', 'Hovězí mleté maso', 'Potraviny', 'kg'),
  ('hovezi-na-gulas', 'Hovězí na guláš', 'Potraviny', 'kg'),
  ('kruti-prsa', 'Krůtí prsa a řízky', 'Potraviny', 'kg'),
  ('kruti-stehna', 'Krůtí stehna', 'Potraviny', 'kg'),
  ('kruti-mlete', 'Krůtí mleté maso', 'Potraviny', 'kg'),
  ('mlete-smesne', 'Mleté maso vepřovo-hovězí', 'Potraviny', 'kg'),
  ('sunka', 'Šunka', 'Potraviny', 'kg'),
  ('parky', 'Párky', 'Potraviny', 'kg'),
  ('slanina', 'Slanina', 'Potraviny', 'kg'),
  ('losos', 'Losos', 'Potraviny', 'kg'),
  ('tunak-konzerva', 'Tuňák v konzervě', 'Potraviny', 'kg'),
  ('ryze', 'Rýže', 'Potraviny', 'kg'),
  ('testoviny', 'Těstoviny', 'Potraviny', 'kg'),
  ('mouka-hladka', 'Mouka hladká', 'Potraviny', 'kg'),
  ('mouka-polohruba', 'Mouka polohrubá', 'Potraviny', 'kg'),
  ('mouka-hruba', 'Mouka hrubá', 'Potraviny', 'kg'),
  ('cukr-krupice', 'Cukr krupice a krystal', 'Potraviny', 'kg'),
  ('cukr-moucka', 'Cukr moučka', 'Potraviny', 'kg'),
  ('olej-slunecnicovy', 'Slunečnicový olej', 'Potraviny', 'l'),
  ('olej-repkovy', 'Řepkový olej', 'Potraviny', 'l'),
  ('olej-olivovy', 'Olivový olej', 'Potraviny', 'l'),
  ('sul', 'Sůl', 'Potraviny', 'kg'),
  ('drozdi', 'Droždí', 'Potraviny', 'kg'),
  ('kava-mleta', 'Káva mletá', 'Potraviny', 'kg'),
  ('kava-zrnkova', 'Káva zrnková', 'Potraviny', 'kg'),
  ('voda-neperliva', 'Voda neperlivá', 'Potraviny', 'l'),
  ('voda-perliva', 'Voda perlivá', 'Potraviny', 'l'),
  ('pivo', 'Pivo', 'Potraviny', 'l'),
  ('toaletni-papir', 'Toaletní papír', 'Drogerie', 'ks'),
  ('kuchynske-uterky', 'Kuchyňské utěrky', 'Domácnost', 'ks'),
  ('zubni-pasta', 'Zubní pasta', 'Drogerie', 'ks'),
  ('sprchovy-gel', 'Sprchový gel', 'Drogerie', 'l'),
  ('sampon', 'Šampon', 'Drogerie', 'l'),
  ('praci-prostredek', 'Prací prostředek', 'Drogerie', 'ks'),
  ('tablety-do-mycky', 'Tablety do myčky', 'Drogerie', 'ks'),
  ('jar', 'Prostředek na nádobí', 'Drogerie', 'l'),
  ('pleny', 'Pleny', 'Děti', 'ks')
ON CONFLICT ("key") DO UPDATE SET "name" = EXCLUDED."name", "category" = EXCLUDED."category", "unit" = EXCLUDED."unit";--> statement-breakpoint
INSERT INTO "product_type_groups" ("key", "name") VALUES
  ('kureci-maso', 'Kuřecí maso'),
  ('veprove-maso', 'Vepřové maso'),
  ('hovezi-maso', 'Hovězí maso'),
  ('kruti-maso', 'Krůtí maso'),
  ('mlete-maso', 'Mleté maso'),
  ('syr', 'Sýr'),
  ('mleko', 'Mléko'),
  ('smetana', 'Smetana'),
  ('mouka', 'Mouka'),
  ('cukr', 'Cukr'),
  ('olej', 'Olej'),
  ('voda', 'Voda'),
  ('kava', 'Káva')
ON CONFLICT ("key") DO UPDATE SET "name" = EXCLUDED."name";--> statement-breakpoint
INSERT INTO "product_type_group_members" ("group_id", "type_id")
SELECT g."id", t."id" FROM (VALUES
  ('kureci-maso', 'kureci-prsa'),
  ('kureci-maso', 'kureci-stehna'),
  ('kureci-maso', 'kureci-kridla'),
  ('kureci-maso', 'kure-cele'),
  ('kureci-maso', 'kureci-mlete'),
  ('kureci-maso', 'kureci-vnitrnosti'),
  ('kureci-maso', 'kureci-na-polevku'),
  ('veprove-maso', 'veprova-krkovice'),
  ('veprove-maso', 'veprova-pecene'),
  ('veprove-maso', 'veprova-panenka'),
  ('veprove-maso', 'veprova-kyta'),
  ('veprove-maso', 'veprova-plec'),
  ('veprove-maso', 'veprovy-bucek'),
  ('veprove-maso', 'veprova-zebra'),
  ('veprove-maso', 'veprove-mlete'),
  ('veprove-maso', 'veprove-na-gulas'),
  ('hovezi-maso', 'hovezi-svickova'),
  ('hovezi-maso', 'hovezi-zadni'),
  ('hovezi-maso', 'hovezi-predni'),
  ('hovezi-maso', 'hovezi-steak'),
  ('hovezi-maso', 'hovezi-mlete'),
  ('hovezi-maso', 'hovezi-na-gulas'),
  ('kruti-maso', 'kruti-prsa'),
  ('kruti-maso', 'kruti-stehna'),
  ('kruti-maso', 'kruti-mlete'),
  ('mlete-maso', 'kureci-mlete'),
  ('mlete-maso', 'veprove-mlete'),
  ('mlete-maso', 'hovezi-mlete'),
  ('mlete-maso', 'kruti-mlete'),
  ('mlete-maso', 'mlete-smesne'),
  ('syr', 'eidam'),
  ('syr', 'gouda'),
  ('syr', 'mozzarella'),
  ('syr', 'balkansky-syr'),
  ('syr', 'hermelin'),
  ('syr', 'parmazan'),
  ('syr', 'taveny-syr'),
  ('syr', 'niva'),
  ('syr', 'cottage'),
  ('mleko', 'mleko-polotucne'),
  ('mleko', 'mleko-plnotucne'),
  ('mleko', 'mleko-bez-laktozy'),
  ('smetana', 'smetana-na-vareni'),
  ('smetana', 'smetana-ke-slehani'),
  ('smetana', 'zakysana-smetana'),
  ('mouka', 'mouka-hladka'),
  ('mouka', 'mouka-polohruba'),
  ('mouka', 'mouka-hruba'),
  ('cukr', 'cukr-krupice'),
  ('cukr', 'cukr-moucka'),
  ('olej', 'olej-slunecnicovy'),
  ('olej', 'olej-repkovy'),
  ('olej', 'olej-olivovy'),
  ('voda', 'voda-neperliva'),
  ('voda', 'voda-perliva'),
  ('kava', 'kava-mleta'),
  ('kava', 'kava-zrnkova')
) AS m("group_key", "type_key")
JOIN "product_type_groups" g ON g."key" = m."group_key"
JOIN "product_types" t ON t."key" = m."type_key"
ON CONFLICT DO NOTHING;
