-- Product types added to lib/product-types.ts from the taxonomy seed proposal (docs/12), batches 8-15:
-- drinks and alcohol, dairy and cheese, sweets, meat, snacks, ready meals, produce, baking, hair/body
-- care, hosiery, supplements, cleaning and baby goods. Insert-only, so it is safe to run before the code
-- that classifies by them is live. No product is reassigned here: `scripts/apply-product-types-batch.ts`
-- does that, after a dry run on the real catalog.

INSERT INTO "product_types" ("key", "name", "category", "unit") VALUES
  ('kombucha', 'Kombucha', 'Potraviny', 'l'),
  ('nealko-pivo', 'Nealkoholické pivo', 'Potraviny', 'l'),
  ('ledove-caje', 'Ledové čaje', 'Potraviny', 'l'),
  ('voda-ochucena', 'Ochucená voda', 'Potraviny', 'l'),
  ('mlecne-napoje', 'Mléčné nápoje', 'Potraviny', 'l'),
  ('kysane-napoje', 'Kysané mléčné nápoje', 'Potraviny', 'l'),
  ('likery', 'Likéry', 'Potraviny', 'l'),
  ('cidery', 'Cidery', 'Potraviny', 'l'),
  ('cerstvy-syr', 'Čerstvý a smetanový sýr', 'Potraviny', 'kg'),
  ('syr-tvrdy', 'Sýr tvrdý a polotvrdý', 'Potraviny', 'kg'),
  ('mlecne-dezerty', 'Mléčné dezerty a pudinky', 'Potraviny', 'kg'),
  ('mleko-kozi-ovci', 'Kozí a ovčí mléko', 'Potraviny', 'l'),
  ('bonboniery', 'Bonboniéry a pralinky', 'Potraviny', 'kg'),
  ('dorty-zakusky', 'Dorty a zákusky', 'Potraviny', 'ks'),
  ('kachna', 'Kachní maso', 'Potraviny', 'kg'),
  ('susene-maso', 'Sušené maso', 'Potraviny', 'kg'),
  ('vyvary-bujony', 'Vývary a bujóny', 'Potraviny', 'kg'),
  ('tlacenky-jitrnice', 'Tlačenka, jitrnice a jelito', 'Potraviny', 'kg'),
  ('arasidy', 'Arašídy', 'Potraviny', 'kg'),
  ('popcorn', 'Popcorn', 'Potraviny', 'kg'),
  ('krekry', 'Krekry', 'Potraviny', 'kg'),
  ('slane-tycinky-preclik', 'Preclíky a slané tyčinky', 'Potraviny', 'kg'),
  ('tortilla-chipsy', 'Tortilla chipsy a nachos', 'Potraviny', 'kg'),
  ('krupky-snacky', 'Křupky', 'Potraviny', 'kg'),
  ('polevky', 'Polévky', 'Potraviny', 'kg'),
  ('pizza-hotova', 'Pizza hotová', 'Potraviny', 'ks'),
  ('salaty-hotove', 'Hotové saláty', 'Potraviny', 'kg'),
  ('sendvice-wrapy', 'Sendviče a wrapy', 'Potraviny', 'ks'),
  ('kvasena-zelenina', 'Kvašená zelenina', 'Potraviny', 'kg'),
  ('instantni-nudle', 'Instantní nudle', 'Potraviny', 'kg'),
  ('ovoce-exoticke', 'Exotické ovoce', 'Potraviny', 'kg'),
  ('kukurice', 'Kukuřice', 'Potraviny', 'kg'),
  ('dyne', 'Dýně', 'Potraviny', 'kg'),
  ('spenat', 'Špenát', 'Potraviny', 'kg'),
  ('cervena-repa', 'Červená řepa', 'Potraviny', 'kg'),
  ('kvetak', 'Květák', 'Potraviny', 'kg'),
  ('knedliky', 'Knedlíky a noky', 'Potraviny', 'kg'),
  ('testo', 'Těsto', 'Potraviny', 'kg'),
  ('smesi-na-peceni', 'Směsi na pečení', 'Potraviny', 'kg'),
  ('barvy-na-vlasy', 'Barvy na vlasy', 'Drogerie', 'ks'),
  ('vlasova-pece', 'Vlasová péče', 'Drogerie', 'ks'),
  ('styling-vlasy', 'Stylingové přípravky na vlasy', 'Drogerie', 'ks'),
  ('telova-pece', 'Tělová péče', 'Drogerie', 'ks'),
  ('krem-na-ruce', 'Krém na ruce', 'Drogerie', 'ks'),
  ('balzam-na-rty', 'Balzám na rty', 'Drogerie', 'ks'),
  ('opalovaci-pripravky', 'Opalovací přípravky', 'Drogerie', 'ks'),
  ('odlicovaci-pripravky', 'Odličovací přípravky', 'Drogerie', 'ks'),
  ('parfemy', 'Parfémy a vůně', 'Drogerie', 'ks'),
  ('pece-o-nehty', 'Péče o nehty', 'Drogerie', 'ks'),
  ('kondomy', 'Kondomy', 'Drogerie', 'ks'),
  ('puncochy', 'Punčochové kalhoty', 'Drogerie', 'ks'),
  ('ponozky', 'Ponožky', 'Drogerie', 'ks'),
  ('bryle', 'Brýle', 'Drogerie', 'ks'),
  ('kontaktni-cocky', 'Kontaktní čočky', 'Drogerie', 'ks'),
  ('vitaminy-doplnky', 'Vitamíny a doplňky stravy', 'Drogerie', 'ks'),
  ('praci-kapsle', 'Prací kapsle', 'Drogerie', 'ks'),
  ('wc-bloky', 'WC bloky a závěsy', 'Drogerie', 'ks'),
  ('rukavice-uklid', 'Rukavice na úklid', 'Drogerie', 'ks'),
  ('osvezovace', 'Osvěžovače', 'Drogerie', 'ks'),
  ('dudliky', 'Dudlíky', 'Děti', 'ks'),
  ('detske-lahve', 'Kojenecké lahve', 'Děti', 'ks'),
  ('detske-kase', 'Dětské kaše', 'Děti', 'kg'),
  ('kojenecke-mleko', 'Kojenecké mléko', 'Děti', 'kg')
ON CONFLICT ("key") DO UPDATE SET
  "name" = EXCLUDED."name",
  "category" = EXCLUDED."category",
  "unit" = EXCLUDED."unit";
