-- Product types added to lib/product-types.ts in batches 16-20 (docs/12): dairy specialities, meat cuts
-- and ready meat, sweets and bars, juices/energy/protein/ready-to-drink and spirits, cosmetics and
-- accessories. Insert-only, so it is safe to run before the code that classifies by them is live. No
-- product is reassigned here: `scripts/apply-product-types-batch.ts` does that, after a dry run on the
-- real catalog.

INSERT INTO "product_types" ("key", "name", "category", "unit") VALUES
  ('syr-plisnovy', 'Plísňový sýr', 'Potraviny', 'kg'),
  ('syr-grilovaci', 'Sýr na gril a pánev', 'Potraviny', 'kg'),
  ('smetana-do-kavy', 'Smetana a mléko do kávy', 'Potraviny', 'l'),
  ('slehacka-sprej', 'Šlehačka ve spreji', 'Potraviny', 'kg'),
  ('creme-fraiche', 'Crème fraîche', 'Potraviny', 'kg'),
  ('ghi', 'Přepuštěné máslo (ghí)', 'Potraviny', 'kg'),
  ('mleko-susene', 'Sušené mléko', 'Potraviny', 'kg'),
  ('mleko-kondenzovane', 'Kondenzované mléko', 'Potraviny', 'kg'),
  ('syrovatka', 'Syrovátka', 'Potraviny', 'l'),
  ('syrove-svacinky', 'Sýrové tyčinky a svačinky', 'Potraviny', 'kg'),
  ('uzene-maso', 'Uzené maso', 'Potraviny', 'kg'),
  ('sekana', 'Sekaná pečeně', 'Potraviny', 'kg'),
  ('kabanos', 'Kabanos a tyčinky z uzeniny', 'Potraviny', 'kg'),
  ('vnitrnosti', 'Vnitřnosti', 'Potraviny', 'kg'),
  ('veprovy-bok', 'Vepřový bok a bůček', 'Potraviny', 'kg'),
  ('hovezi-zebra', 'Hovězí žebra', 'Potraviny', 'kg'),
  ('zverina-kralik', 'Zvěřina a králík', 'Potraviny', 'kg'),
  ('pecene-maso-hotove', 'Pečené maso hotové', 'Potraviny', 'kg'),
  ('hotova-masova-jidla', 'Hotová masová jídla', 'Potraviny', 'kg'),
  ('kureci-nugety-stripsy', 'Nugety a stripsy', 'Potraviny', 'kg'),
  ('maso-nudlicky-kostky', 'Masové nudličky a kostky', 'Potraviny', 'kg'),
  ('kureci-rizky', 'Kuřecí řízky a závitky', 'Potraviny', 'kg'),
  ('trhane-maso', 'Trhané maso', 'Potraviny', 'kg'),
  ('maso-ve-vlastni-stave', 'Maso ve vlastní šťávě (konzerva)', 'Potraviny', 'kg'),
  ('masove-smesi-na-polevku', 'Masová směs na polévku', 'Potraviny', 'kg'),
  ('veprove-koleno', 'Vepřové koleno a výpečky', 'Potraviny', 'kg'),
  ('veprove-vedlejsi', 'Vepřové nožky, uši a hlava', 'Potraviny', 'kg'),
  ('kruti-ostatni', 'Krůtí krk, křídla a vnitřnosti', 'Potraviny', 'kg'),
  ('sous-vide-maso', 'Maso sous-vide', 'Potraviny', 'kg'),
  ('burgery', 'Burgery', 'Potraviny', 'kg'),
  ('proteinove-tycinky', 'Proteinové tyčinky a sušenky', 'Potraviny', 'kg'),
  ('cerealni-tycinky', 'Cereální a ovesné tyčinky', 'Potraviny', 'kg'),
  ('pernik', 'Perník a perníčky', 'Potraviny', 'kg'),
  ('puding-prasek', 'Pudink a krém v prášku', 'Potraviny', 'kg'),
  ('marshmallow', 'Marshmallow a pěnové cukrovinky', 'Potraviny', 'kg'),
  ('cokolada-na-vareni', 'Čokoláda na vaření', 'Potraviny', 'kg'),
  ('orechy-v-cokolade', 'Pochutiny v čokoládě', 'Potraviny', 'kg'),
  ('adventni-kalendare', 'Adventní kalendáře a sezónní sladkosti', 'Potraviny', 'ks'),
  ('energeticke-napoje', 'Energetické nápoje', 'Potraviny', 'l'),
  ('mosty', 'Mošty', 'Potraviny', 'l'),
  ('ovocne-stavy-100', 'Ovocné šťávy a nápoje', 'Potraviny', 'l'),
  ('napojove-koncentraty', 'Nápojové koncentráty', 'Potraviny', 'l'),
  ('kokosova-voda', 'Kokosová voda', 'Potraviny', 'l'),
  ('iontove-napoje', 'Iontové a sportovní nápoje', 'Potraviny', 'l'),
  ('proteinove-napoje', 'Proteinové nápoje', 'Potraviny', 'l'),
  ('kavove-napoje-hotove', 'Hotové kávové nápoje', 'Potraviny', 'l'),
  ('instantni-napoje', 'Instantní nápoje v prášku', 'Potraviny', 'kg'),
  ('medovina', 'Medovina', 'Potraviny', 'l'),
  ('fortifikovana-vina', 'Portské, sherry a vermut', 'Potraviny', 'l'),
  ('rtd-koktejly', 'Hotové míchané nápoje', 'Potraviny', 'l'),
  ('palenky', 'Pálenky a destiláty', 'Potraviny', 'l'),
  ('suchy-sampon', 'Suchý šampon', 'Drogerie', 'l'),
  ('kosmeticke-pomucky', 'Kosmetické štětce a pomůcky', 'Drogerie', 'ks'),
  ('vlasove-doplnky', 'Doplňky do vlasů', 'Drogerie', 'ks'),
  ('umele-nehty', 'Umělé nehty a doplňky', 'Drogerie', 'ks'),
  ('depilace', 'Depilace', 'Drogerie', 'ks'),
  ('pece-o-nohy', 'Péče o nohy', 'Drogerie', 'ks'),
  ('koupel', 'Přípravky do koupele', 'Drogerie', 'l'),
  ('lubrikacni-gely', 'Lubrikační gely', 'Drogerie', 'ks'),
  ('univerzalni-krem', 'Univerzální a výživný krém', 'Drogerie', 'ks'),
  ('zubni-nahrady', 'Péče o zubní náhrady', 'Drogerie', 'ks')
ON CONFLICT ("key") DO UPDATE SET
  "name" = EXCLUDED."name",
  "category" = EXCLUDED."category",
  "unit" = EXCLUDED."unit";
