// Worker entry for the Cloudflare build (wrangler.jsonc `main`). Not used by the Vercel deployment.
//
// OpenNext generates `.open-next/worker.js`, which serves every HTTP request. It has no `scheduled()`
// handler, so this wraps it and adds one: each Cron Trigger calls the matching /api/cron/* route
// through the same Worker, exactly as Vercel Cron calls it today (see cloudflare/cron.ts).

// @ts-ignore — generated by `opennextjs-cloudflare build`; missing until the first Cloudflare build.
import openNextWorker from '../.open-next/worker.js'
import { cronPaths, cronRequest } from './cron'

// Minimal shapes of the Workers runtime types this file uses, so it type-checks without adding
// @cloudflare/workers-types to the project.
type ExecutionContext = { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void }
type ScheduledController = { cron: string; scheduledTime: number }
type Env = { CRON_SECRET?: string } & Record<string, unknown>
type FetchHandler = (request: Request, env: Env, ctx: ExecutionContext) => Promise<Response>

const fetchHandler: FetchHandler = (openNextWorker as { fetch: FetchHandler }).fetch

export default {
  fetch: fetchHandler,

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    const paths = cronPaths(controller.cron)
    if (paths.length === 0) {
      console.warn(JSON.stringify({ event: 'cron_unknown_schedule', cron: controller.cron }))
      return
    }

    const failures: string[] = []
    // One after another, like separate Vercel invocations would not overlap a single schedule.
    for (const path of paths) {
      const startedAt = Date.now()
      const response = await fetchHandler(cronRequest(path, env.CRON_SECRET), env, ctx)
      const ok = response.ok
      await response.body?.cancel()
      console.log(JSON.stringify({ event: 'cron_run', cron: controller.cron, path, status: response.status, ms: Date.now() - startedAt }))
      if (!ok) failures.push(`${path} → ${response.status}`)
    }
    // Throwing marks the invocation as failed in the Workers dashboard instead of hiding it.
    if (failures.length > 0) throw new Error(`Cron jobs failed: ${failures.join(', ')}`)
  },
}
